### ISSUE TITLE
Resampling of integer channels

### ISSUE THREAD

**Issue by cristi-neagu** [ratal/mdfreader#101]
Resampling integer channels should not be done with linear interpolation (np.interp). Consider using scipy.interpolate.interp1d(kind='zero') instead. This could be hardcoded, or, if more flexibility is desired, give the user the option to specify zero order interpolation for integer signals.

The downside is that it would introduce an extra dependency on scipy in the mdf module.

**Comment by danielhrisca** [comment]
Hello Cristi,

this is similar to issue #90

**Comment by cristi-neagu** [comment]
It is, yes. I didn't notice it because it was a secondary issue, different from the original title. In any case, i feel it merits its own tracker.

**Comment by ratal** [comment]
Thanks for the tip Cristi
yes indeed already issued, thanks Daniel, definitely needed :)
scipy is already an optional dependency for export to netcdf or matlab, so why not adding this interpolation.
however I am wondering how it performs against searchsorted used by Daniel ?

**Comment by cristi-neagu** [comment]
On my system, scipy does perform 2-3 times worse than searchsorted, over about 765000 data points. The worst performance i got was about 60ms, which is still reasonably fast. Both methods work just as well. Searchsorted has the advantage of speed, while scipy is more readable, in my opinion.

**Comment by danielhrisca** [comment]
@cristi-neagu nice find. It does exactly what my implementation does; I'm thinking of adding script to the dependency list and use interp1d

**Comment by danielhrisca** [comment]
After a few tests it seems that interp1d is 3x slower and raises exception for new timestamps outside the initial timestamp interval.

**Comment by cristi-neagu** [comment]
interp1d can be asked to either replace any values outside of bounds with given values, or extrapolate data, by using `fill_value`.

**Comment by danielhrisca** [comment]
You're right. One has to decide if the speed penalty is acceptable or not.

**Comment by ratal** [comment]
Hi,
I put Daniel's snippet (thanks) for interpolation in last mdfreader commit.
Can you check if that suits you ?

**Comment by cristi-neagu** [comment]
That code works perfectly. Thanks.

**Comment by cristi-neagu** [comment]
Fixed in d1d9a45
