### ISSUE TITLE
comment readed by the latest version is None 

### ISSUE THREAD

**Issue by aqkfatmtvvfb** [ratal/mdfreader#110]
ver 884b10 is right 2017/10/24 03:19:58

ver 76fbc5 is wrong 2017/11/14 06:35:30

ps:
i run mdfreader a few days ago and i obtained desired result, then i run it again today and find this error.
i reinstalled mdfreader and cython by pip and 'python install'
when i want to give up ,i find the problem finally, and a whole day is passed by..

**Comment by ratal** [comment]
Hi,
To help you, I would need a bit more details:
What comment do you mention ? Is it date and time of file ? Which mdf version ?

**Comment by aqkfatmtvvfb** [comment]
@ratal 
**result compare:**

- Right

![right](https://user-images.githubusercontent.com/4980148/32784839-e74a8a06-c98a-11e7-91ba-f4c2ab338af3.jpg)

- Wrong

![wrong](https://user-images.githubusercontent.com/4980148/32784859-f4f2d55a-c98a-11e7-9656-a863d6ca6616.jpg)

-  Info

![info](https://user-images.githubusercontent.com/4980148/32784869-fa0fa374-c98a-11e7-8bfc-5ff4ed3739ac.jpg)

**Comment by ratal** [comment]
Last commit should have fixed it.
line 846 was still having ['Text'], should be removed, it was from previous implementation of info reading.

**Comment by ratal** [comment]
For #114, I improved further the header reading.
Can you please check or close this issue if you are ok with it.
