### ISSUE TITLE
Bug in mdfinfo3.read_cc_block for case cc_type == 12 (text range table)

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#111]
Hi,

current version fails to read text look-up value and always uses an empt string instead.

Line 568 in mdfinfo3:
`temp['conversion'][pair]['Textrange'] = read_tx_block(fid, temp[pair]['pointerToTXBlock'])`

must be changed to:
`temp['conversion'][pair]['Textrange'] = read_tx_block(fid, temp['conversion'][pair]['pointerToTXBlock'])`

**Comment by ratal** [comment]
That is I think causing same issue as in #112

**Comment by ginseil** [comment]
This is fixed for me. Thanks!
