### ISSUE TITLE
Support for CANape specific features

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#112]
Hi

do you plan to add support for CANape specific features like the following one?
![image](https://user-images.githubusercontent.com/7522976/32779259-4b4ce36c-c93d-11e7-9dc5-19144a255bd1.png)

**Comment by danielhrisca** [comment]
What you see here is partial conversion and it is a part of the MDF standard.

**Comment by ratal** [comment]
I guess you do not have a converted channel.
I found a bug in mdfinfo3 that could have caused this, should  be fixed in last commit, please try.

**Comment by ginseil** [comment]
What I mean is that the defined macro in the default value is applied before the simple range to text mapping is done.

**Comment by ratal** [comment]
Let me confirm: you expect that default value becomes a linear conversion, not a text ?
Similar conversion is existing in mdf4. Possible but I am wondreing how to trigger it. With keyword 'LINEAR CONV' ?
Maybe more examples of it would help a bit to get how CANape is doing...

**Comment by ginseil** [comment]
Let me confirm: you expect that default value becomes a linear conversion, not a text ?
> Yes.

Similar conversion is existing in mdf4. Possible but I am wondreing how to trigger it. With keyword 'LINEAR CONV' ?
> I think a macro function is surrounded by curly braces, staring with the name of the formula: 'LINEAR_CONV'.

**Comment by ratal** [comment]
I am currently working on this:
```
        npair = len(conv)
        lower = [conv[pair]['lowerRange'] for pair in range(npair)]
        upper = [conv[pair]['upperRange'] for pair in range(npair)]
        text = {}
        for pair in range(npair):
            text[pair] = conv[pair]['Textrange']
            if 'LINEAR CONV' in text[pair]:  # linear conversion from CANape
                from sympy import lambdify, symbols
                X = symbols('X')  # variable is X
                left = text[pair].find('"')
                right = text[pair].rfind('"')
                text[pair] = text[pair][left + 1: right].replace('{', '').replace('}', '')
                text[pair] = lambdify(X, text[pair], modules='numpy', dummify=False)
        temp = []
        for Lindex in range(len(data)):
            value = text[0]  # default value
            for pair in range(1, npair):
                if lower[pair] <= data[Lindex] <= upper[pair]:
                    value = text[pair]
                    break
            if callable(value):
                value = value(data[Lindex])
            temp.append(value)
```
Can you check if it would be working for you ? unfortunately, the callable() is giving performance penalty

**Comment by ginseil** [comment]
Hi, I'll test it in the next few days. Thanks for your work!

**Comment by ginseil** [comment]
There is a bug in your code: `if 'LINEAR CONV' in text[pair]:  # linear conversion from CANape`

I miss the underscore in LINEAR_CONV.
However your solution works, once the underscore is added.

**Comment by ratal** [comment]
Good, I will correct and put in master

**Comment by ratal** [comment]
Part of last commit, you can check

**Comment by ginseil** [comment]
Works like a charm, Thank you! :)

**Comment by danielhrisca** [comment]
@ginseil 

I'm trying to replicate this CANape specific feature, however MDFValidator doesn't raise this warning for my file:

![image](https://user-images.githubusercontent.com/20952040/36597160-ed45342c-18b0-11e8-9f60-1c7c2b3354ea.png)

The conversion block seems to me identical to what you had in your measurement. Is there something else that I don't see?

**Comment by danielhrisca** [comment]
I missed the underscore in _LINEAR_CONV_.
