### ISSUE TITLE
mdf_info['HD']['Comment'] is incomplete for MDF 4 files

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#114]
Hi,

I am missing some data in mdf['HD']['Comment']:
![image](https://user-images.githubusercontent.com/7522976/32895751-67a88f20-cae1-11e7-8514-889bafcfc683.png)

The Comment is parsed and loaded for this XML content:
`<HDcomment xmlns="http://www.asam.net/mdf/v4">
  <TX>ASAM MDF 4.0 Example file created by ETAS. Contents: 2 simple channel groups containing ints and floats in little endian format.</TX>
  <time_source>PC timer</time_source>
  <common_properties>
    <e name="subject">Example</e>
    <e name="project">ASAM Example Files</e>
    <e name="department">ETAS GmbH</e>
    <e name="author">Tobias Langner</e>
  </common_properties>
</HDcomment>`

As can be seen the XML has content for TX and time_source but TX is parsed to None and time_source does not exist at all. Only the properties in common_properties are read.

**Comment by danielhrisca** [comment]
It is probably linked to the issue #99 

Using _find_ instead of xpath works better:
https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf4.py#L3395

**Comment by ratal** [comment]
I switched from etree/xpath to objectify, should be better working.
small performance downside but as it was not working before, maybe not relevant.
Please check.

**Comment by ginseil** [comment]
Works like a charm, thanks!
