### ISSUE TITLE
Cannot instantiate

### ISSUE THREAD

**Issue by found36** [ratal/mdfreader#115]
I can't instantiate a module.
***code ******
# -*- coding: utf-8 -*-
import mdfreader
NameofFile = r'C:\Users\Administrator\Desktop\S5_CVT_emission_0801\S5_CVT_emission_0801.dat'
yop = mdfreader.mdf(NameofFile)
*********

C:\Python27\python.exe C:/Users/Administrator/PycharmProjects/Charger_BMS_TEST/TestPrint.py
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Charger_BMS_TEST/TestPrint.py", line 4, in <module>
    yop = mdfreader.mdf(NameofFile)
  File "C:\Python27\lib\site-packages\mdfreader\mdf.py", line 146, in __init__
    compression=compression)
  File "C:\Python27\lib\site-packages\mdfreader\mdfreader.py", line 398, in read
    convertAfterRead, filterChannelNames, compression)
  File "C:\Python27\lib\site-packages\mdfreader\mdf3reader.py", line 889, in read3
    buf.read(channelSet)  # reads datablock potentially containing several channel groups
  File "C:\Python27\lib\site-packages\mdfreader\mdf3reader.py", line 686, in read
    nameList=channelSet)
  File "C:\Python27\lib\site-packages\mdfreader\mdf3reader.py", line 712, in loadSorted
    return record.readSortedRecord(self.fid, self.pointerToData, nameList)
  File "C:\Python27\lib\site-packages\mdfreader\mdf3reader.py", line 470, in readSortedRecord
    buf = recarray(self.numberOfRecords, channel_format)  # initialise array
  File "C:\Python27\lib\site-packages\numpy\core\records.py", line 414, in __new__
    descr = sb.dtype(dtype)
TypeError: data type not understood

**Comment by found36** [comment]
![untitled](https://user-images.githubusercontent.com/10473527/33009033-5975a294-ce10-11e7-9966-08c6898a5186.png)

**Comment by ratal** [comment]
Hi,
Can you mention which version you are using ?
To start troubleshooting, can you print channel_format before the call of recarray initialisation ?

**Comment by found36** [comment]
Thanks for your reply.
![image](https://user-images.githubusercontent.com/10473527/33057791-9040060e-cec7-11e7-9732-c166a2c92f7f.png)

**Comment by found36** [comment]
![image](https://user-images.githubusercontent.com/10473527/33057853-c3c07810-cec7-11e7-9850-a40366176079.png)

**Comment by ratal** [comment]
ok, 2.7.1
It was not clear from me, can you insert 'print(channel_format)' before the line 470 in mdf3reader.py and report here the output ?
Reason: a numpy dtype seems not correct, so let's have a look at it, maybe a strange channel name.

**Comment by found36** [comment]
it is ok when I reinstall mdfreader 0.2.7
thank you very much.

**Comment by ratal** [comment]
It means there is potentially regression between 0.2.7 to 2.7.1 ... 
If you have time to investigate, can I kindly ask you to send this print, otherwise close the issue ?

**Comment by found36** [comment]
![image](https://user-images.githubusercontent.com/10473527/33104744-a9332018-cf64-11e7-8034-ae797c52b844.png)

[(('time_title', u'time'), '<f8'), (('ABS_RRWheelSpeed_title', u'ABS_RRWheelSpeed'), '<u2'), (('ABS_RLWheelSpeed_title', u'ABS_RLWheelSpeed'), '<u2'), (('ABS_FRWheelSpeed_title', u'ABS_FRWheelSpeed'), '<u2'), (('ABS_FLWheelSpeed_title', u'ABS_FLWheelSpeed'), '<u2')]

**Comment by ratal** [comment]
I coudl notice a regression with python 2.7 and these channel naming issue.
I am working on a fix.

**Comment by ratal** [comment]
I made a fix in last commit only for mdf3 for the moment, you can try it.

**Comment by found36** [comment]
Thanks

**Comment by ratal** [comment]
If it works for you, please close the issue
