### ISSUE TITLE
Issue with mdfinfo3.readCGBlock handling of duplicate channel names

### ISSUE THREAD

**Issue by cristi-neagu** [ratal/mdfreader#117]
Hello,

`mdfinfo3.readCGBlock` handles duplicate channel names by appending the datagroup number to their name. But if the duplicates are all inside the same datagroup, this causes an error in `mdf3reader.readSortedRecord` when creating the recarray, due to duplicate names (`Value Error: name already used as a name or title`).

Unfortunately, i cannot share the mdf file that causes this issue, but i can investigate further, if needed.

**Comment by ratal** [comment]
Hi,
Dupmicate names should happen in case of unsorted data but it should be avoided by line 223 in mdfinfo3.  Something went wrong there, key 'ChannelNamesByDG' might be wrong, can you check ?

**Comment by cristi-neagu** [comment]
Hello,

Good call. The signal in question has a long name (41 characters). As such, `signalName` and `self['CNBlock'][dg][cg][channel]['signalName']` are not the same, since the first contains the long name (from line 209), and the latter has the short name. In line 221 you are checking for what basically is the short name in `self['ChannelNamesByDG'][dg]`, but with line 230 you effectively put the long name in that list. As such, the check on line 221 you will always return `False`. Line 224 will pick up the duplicate, will append the dg number to it, and move on. This will catch situations with two duplicates, but not situations with more than two duplicates, such as in my case.

So, basically, this is the order of events, keeping in mind that `self['CNBlock'][dg][cg][channel]['signalName']` contains the short name, and `signalName` contains the long name:

- the check on line 221 returns `False`
- the check on line 224 returns `False`
- line 228 replaces the short name with the long name
- lines 229 and 230 save the long name in `self['ChannelNamesByDG'][dg]` and in `self['allChannelList']`
- for the next label, line 221 returns `False`, because that list contains the long name
- line 224 returns `True`, because we're checking the long name, and the `dg` number is appended
- lines 229 and 230 save the long name with the appended `dg` to the lists

The last 3 lines repeat for every other occurrence, leading to multiple channels with the same name, with the `dg` attached.

Seems like the solution is to use `signalName` instead of `self['CNBlock'][dg][cg][channel]['signalName']`

**Comment by ratal** [comment]
Hi,
Thanks for the investigation, very clear and you are right. I corrected it I think according to your proposal in last commit, you can check it.

**Comment by cristi-neagu** [comment]
Hello,

Works now. No errors during file load and channels are getting the correct termination.

Thanks!
