### ISSUE TITLE
":" not in signal name

### ISSUE THREAD

**Issue by rolfub** [ratal/mdfreader#119]
Hello Aymeric,

is it possible that you filter ":" out of signal names?
I miss them in masterChannelList().

Yours sincerely,

Rolf

**Comment by ratal** [comment]
Hi Rolf,
Possible for version before 2.7.2 Which one are you using ? And mdf version ?
There was annoying issues with channel names and python attributes names limitation for recarrays (issue #109 )
If you export, there are limitations for the variable naming, especially with Matlab.
Aymeric

**Comment by rolfub** [comment]
Hello Aymeric,

we use version 2.7.2.
The file has mdf version 4.1.
Numpy version is 1.11.1.

Rolf

**Comment by danielhrisca** [comment]
Hello Rolf, 

as seen in #109 if you use numpy 1.13.1 you should not get this error anymore.

**Comment by rolfub** [comment]
Thank you Daniel, we will test it.
Rolf

**Comment by danielhrisca** [comment]
Hello Rolf,
 we should all thank the bumpy guys :)

**Comment by ratal** [comment]
Hi Rolf,
I just found a `self['name'] = self['name'].replace(':', '')` at the end of CNBlock.read in mdfinfo4, could be your issue.
No reason to have this code anymore, I will remove it for next commit.

**Comment by ratal** [comment]
About a month no feedback => issue should be fixed.
Do not hesitate to repoen.
