### ISSUE TITLE
Error when specifying channelList in mdf.read()

### ISSUE THREAD

**Issue by leiber83** [ratal/mdfreader#12]
Hi ratal,

i am trying to reduce the memory consumption of my script by reading just specific channels from my mdf-file. The code I used is:

inca_mdf = mdfreader.mdf()
inca_mdf.read(inca_filepath, channelList=cList)

where cList is an array of strings. Unfortunately this does not work, and I get the following error-message:

  File "aaa", line 43, in Main
    inca_mdf.read(inca_filepath, channelList=cList)

  File "build\bdist.win-amd64\egg\mdfreader\mdfreader.py", line 371, in read
    self.read4(self.fileName, info, multiProc, channelList, convertAfterRead)

  File "build\bdist.win-amd64\egg\mdfreader\mdf4reader.py", line 1162, in read4
    buf.read(channelList)  # reads raw data with DATA and DATABlock classes

  File "build\bdist.win-amd64\egg\mdfreader\mdf4reader.py", line 348, in read
    self[recordID]['data'] = self.load(record, zip=None, nameList=channelList, sortedFlag=True)

  File "build\bdist.win-amd64\egg\mdfreader\mdf4reader.py", line 422, in load
    temps['data'] = DATABlock(record, parent_block=data_block, channelList=nameList, sortedFlag=sortedFlag)

  File "build\bdist.win-amd64\egg\mdfreader\mdf4reader.py", line 88, in DATABlock
    return record.readBitarray(parent_block['data'], channelList)

  File "build\bdist.win-amd64\egg\mdfreader\mdf4reader.py", line 992, in readBitarray
    buf = recarray(self.numberOfRecords, format)

  File "C:\Program Files\Anaconda\lib\site-packages\numpy\core\records.py", line 401, in __new__
    self = ndarray.__new__(subtype, shape, (record, descr), order=order)

ValueError: data-type with unspecified variable length

I am using version 0.1.8 of mdfreader. Is there any way I can solve this?

Best regards

**Comment by ratal** [comment]
Hi Leiber,
What is the exact type of cList ? Array of string is not what is expected, it should be a list of strings.

**Comment by leiber83** [comment]
Hi ratal,
thank you for your quick reply. Sorry, my bad, type(cList) is in fact <type 'list'>

**Comment by ratal** [comment]
If it is working, no problem then.
There is basic documentation in the package if you want to have a look. There is description of methods/functions and related expected types for arguments.
Regards

**Comment by leiber83** [comment]
I think there is a misunderstanding here, I used a list all along, just accidentally wrote array. 
Unfortunately I still get the error, even if I put in the list directly, as specified in the documentation:
inca_mdf.read(inca_filepath,convertAfterRead=False, channelList=['channelName1','channelName2'])

**Comment by ratal** [comment]
A bit difficult to track why there is this problem without your file. If you have the opportunity, can you just print the variable format just before line 992 in mdf4reader/bitarray ?
With version 1.9 which is using cython by default instead of bitarray, I have an error but bitarray fallback function works properly for me -> I have difficulties to reproduce your concern with my test files.

**Comment by leiber83** [comment]
The file is MDF version 4.10 and quite huge. I have added some debug outputs around the code in questions.
My channel list looks like this:
['DFES_numDFC_[0]', 'DFES_stChk_[0]', 'DFES_numDFC_[1]', 'DFES_stChk_[1]', 'DFES_numDFC_[2]', 'DFES_stChk_[2]', 'DFES_numDFC_[3]', 'DFES_stChk_[3]', 'DFES_numDFC_[4]', 'DFES_stChk_[4]', 'DFES_numDFC_[5]', 'DFES_stChk_[5]', 'DFES_numDFC_[6]', 'DFES_stChk_[6]', 'DFES_numDFC_[7]', 'DFES_stChk_[7]', 'DFES_numDFC_[8]', 'DFES_stChk_[8]', 'DFES_numDFC_[9]', 'DFES_stChk_[9]', 'DFES_numDFC_[10]', 'DFES_stChk_[10]', 'DFES_numDFC_[11]', 'DFES_stChk_[11]', 'DFES_numDFC_[12]', 'DFES_stChk_[12]', 'DFES_numDFC_[13]', 'DFES_stChk_[13]', 'DFES_numDFC_[14]', 'DFES_stChk_[14]', 'DFES_numDFC_[15]', 'DFES_stChk_[15]', 'DFES_numDFC_[16]', 'DFES_stChk_[16]', 'DFES_numDFC_[17]', 'DFES_stChk_[17]', 'DFES_numDFC_[18]', 'DFES_stChk_[18]', 'DFES_numDFC_[19]', 'DFES_stChk_[19]']

but if I print the channel.name in the for loop at line 990 in mdf4reader/readBitarray it yields:
time0
TE_101
TE_102
TE_103
TE_104
and therefore the variable "format" will remain empty.
The channel-Data is present in the file. If I read the whole file and get their data with getChannelData(channelName) it works perfectly (but consumes a lot of memory).

**Comment by ratal** [comment]
By putting : 
if format: just before buf = recarray(self.numberOfRecords, format) 
+ indenting everything after in the function, does it solve your concern ?
In lastest git, I changed the channelList definition in order to have always at least the master of data group in list, it should also solve your concern I think.
I advise you to update to 0.1.9 if you make big use of readBitarray function (not byte aligned data or channelList used) as it is now implemented in cython and it is much faster than in 0.1.8 (~x60). However, it is a bit new so I advise you then to upload latest git master (I made some fixes in the mean time for channelList handling)

**Comment by leiber83** [comment]
Inserting if(format) did the trick, thank you!

Although is it possible to add the corresponding master-channels for the channels in the list automatically?

**Comment by ratal** [comment]
The master channels have been included in latest release 0.1.9 or in latest git.
