### ISSUE TITLE
PyInstaller: ModuleNotFoundError: No module named 'mdf3reader'

### ISSUE THREAD

**Issue by joelhjalmarsson** [ratal/mdfreader#120]
I am trying to package my application with pyinstaller. But when executing the .exe file I get the following errors:

Traceback (most recent call last):
  File "site-packages\mdfreader\__init__.py", line 28, in <module>
  File "c:\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mdfreader\mdfreader.py", line 48, in <module>
ModuleNotFoundError: No module named 'mdf3reader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "drivers_notes.py", line 8, in <module>
    from mdfreader import mdf
  File "c:\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mdfreader\__init__.py", line 30, in <module>
ImportError: cannot import name 'mdfinfo'
[5568] Failed to execute script drivers_notes

I have been trying via the pyinstaller support pages to find a way to solve this but I am just too much of a newbie when it comes to python, modules and dependencies. Giving it one last try here in case anyone else has any experience with mdfreader and pyinstaller.

**Comment by danielhrisca** [comment]
_mdfreader_ has an obfuscated import system. Perhaps _pyinstaller_ would succed if #91 would be implemented.

**Comment by ratal** [comment]
Intention was not to obfuscate import system but improve robustness of import process and support people having issues with it by introducing absolute path import. But this is not recommended way of doing indeed, which might cause the issue you are facing with pyinstaller.
reading [this](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#analysis-finding-the-files-your-program-needs), it could be the sys.path modification the problem.
I will try again switching to relative import but in the mean time, I guess you could have a look at the spec files mentionned in the link ?

**Comment by cristi-neagu** [comment]
If absolute path imports are needed for command line functionality, maybe it would be better to add a specific command line frontend? Something for the future.

**Comment by ratal** [comment]
Can you detail about this command line frontend ?
Do you mean what is at the end of mdfreader.py ?

**Comment by danielhrisca** [comment]
```python
import sys

from pprint import pprint

pprint(sys.path)

import mdfreader

pprint(sys.path)
```

**Comment by cristi-neagu** [comment]
> Can you detail about this command line frontend ?

I thought that the sys.path appends were due to some issues with calling the module from the command line. Maybe i misunderstood.

**Comment by ratal** [comment]
Absolute path is rather coming from #41 Let's call it youth mistake.
You can check last commit, switched to relative path, seems to be working, more clean. Does it work better joelhjalmarsson ?

**Comment by joelhjalmarsson** [comment]
Hi. Yes it seems to be working better now. Thanks!
