### ISSUE TITLE
Import of pandas like matplotlib optional?

### ISSUE THREAD

**Issue by rolfub** [ratal/mdfreader#121]
Hello Aymeric,

is it possible to make the import of pandas optional like matplotlib?

Yours sincerely,

Rolf

**Comment by ratal** [comment]
Hi Rolfub,
I do not get it. Both pandas and matplotlib import are in try: except: in mdfreader.py
pandas is optional in setup.py
I realise, matplotlib is not mentionned in setup.py.
What is your issue ?
Aymeric

**Comment by danielhrisca** [comment]
@rolfub What is the reason for not wanting pandas as a required package?

**Comment by rolfub** [comment]
Hello Aymeric,
you are right but there is an additional import of pandas in "mdf.py" (line 30: "from pandas import set_option").
I don't get it myself but there is a colleague who comments out this line because he don't want to install pandas and that isn't a good idea. :-(
So if it isn't a problem for you to change this than it is good. Otherwise I will install pandas for him. :-)
I wish you a Merry Christmas and a Happy New Year!
Rolf

**Comment by ratal** [comment]
Hi Rolfub,
Ok, I forgot this one. Indeed not consistent. I will do same treatment with try: except in next commit
Aymeric

**Comment by ratal** [comment]
About a month no feedback => issue should be fixed.
Do not hesitate to repoen.
