### ISSUE TITLE
Wheel file not possible to instal in 2.7

### ISSUE THREAD

**Issue by Awesterberg** [ratal/mdfreader#122]
mdfread is said to be compatible with both python 2.7 and 3.4+ however the wheel file seems only to work in 3.4x

**Comment by ratal** [comment]
It is compatible with python 2.7 but you might need a wheel only if you want to use the cython module for speed up. You should be able to run mdfreader without it.
The cython module can be compiled as long as you have compiler installed on your machine (advised solution). What is your OS, windows, mac, (no need for linux), 32/64 bit ?
Honestly, there are too many combinations along with python version, sorry I cannot compile a wheel for all of them, I only release one for what I consider main stream, windows 64bit 3.4-6 python.

**Comment by Awesterberg** [comment]
Yes, I have no problem running mdfreader in python 2.7, Windows 10, 64 bit, but I got some difficulties when trying to update to the newest version. I am very new to python so I just thought the wheel installation seems easy and I somewhere read this info: "If your project is python 2 and 3 compatible you can create a universal wheel distribution" ..................  but as I said I am new in this game. In any case mdfreader seems like a great sw!

**Comment by cristi-neagu** [comment]
If you're very new to Python, I have to ask: is there any reason why you're using Python 2 instead of 3?

**Comment by ratal** [comment]
Universal wheel can be applied if cython part is not considered/installed
Cython is a hybrid of python and C language. During install, C code is generated and compiled --> need for wheels.
What is your issue to update to newest version (from which on to which one) ?

**Comment by Awesterberg** [comment]
Problem is solved. Had to do with my numpy installation after uninstalled and installed it again I could update to the newest version of mdfreader. And after learning that pip works as well with "pip install mdfreader-2.7.3.tar.gz" as with wheel, there is no real need for the wheel. 

Python 2.7 instead of 3.x well actually no idea just following my colleagues.
