### ISSUE TITLE
lazy loading for raw values

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#123]
Hi,

I have mdf files with a size in GB and need lazy access to raw values and the calculated ones.

I know I can access the calculated ones using the `noDataLoading = True` flag but I have to open the file with `convertAfterRead=False` to access the raw values. Since I want to process the mdf file channel by channel I'll end up reading the file once again each time I need access to a channel's the raw values...

Could you add the possibility to provide raw values on demand?

**Comment by danielhrisca** [comment]
Hello, why do you need the raw values?

**Comment by ginseil** [comment]
We export them next to the calculated ones.

**Comment by ratal** [comment]
Yes, possible.
By when you need it ? (vacation period coming)

**Comment by ginseil** [comment]
Hmm, probably 15. january...

**Comment by ratal** [comment]
I must admit I never considered and tested combination of both argument noDataLoading and convertAfterRead, but I did a few tests and seems to be working properly, at least I can get back converted channels.
I guess you want to extract both raw and converted data from getChannelData after reading with noDataLoading=True, so I will add it an argument specificly for returning only raw data.

**Comment by ginseil** [comment]
That would be awesome. Thanks!

**Comment by ratal** [comment]
I implemented the argumetn raw_data flag in getChannelData for last commit, you can give a try.

**Comment by ginseil** [comment]
I tried it and it works like a charm. Thanks!
