### ISSUE TITLE
copy method shallow copies data

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#125]
The _copy_ method does just a shallow copy. If you modify a channel in the initial _mdf_ object you will see this in the copied  object as well.

**Comment by ratal** [comment]
Hi Daniel,
Yes indeed this is a shallow copy. I guess you expected a deepcopy() ?
I only had the need for this copy function with mdfconverter in mdfreaderui4/5.py

**Comment by danielhrisca** [comment]
Hello Aymeric,

yes, my first assumption was that it was meant to perform a deep copy

**Comment by ratal** [comment]
What is your use case for this deepcopy in mdfreader ? You are the first one to mention about this.
As mdf class is mostly a dict with a few attributes, it is not that complicated to apply deepcopy I think, but as usual heavy.

**Comment by ratal** [comment]
I made the documentation of this function more clear by stating this is a shallow copy of object. Do you need deepcopy in mdfreader ?

**Comment by danielhrisca** [comment]
The clarification is enough
