### ISSUE TITLE
read MDF4 file

### ISSUE THREAD

**Issue by Nordlxnder** [ratal/mdfreader#128]
Hi ,

 I installed the mdfreader on my linux system and so far it seems that the installation went well, but I tried to import the mdf4reader and got the follow error.  To import mdfreader seems to work. Did I do something wrong or how can I read a mdf4 file? 

Thanks in advanced

/usr/bin/python3.6 /home/golfo/PycharmProjects/mdf4/hauptprogramm.py
Traceback (most recent call last):
  File "/home/golfo/PycharmProjects/mdf4/hauptprogramm.py", line 4, in <module>
    import mdf4reader
ModuleNotFoundError: No module named 'mdf4reader'

**Comment by cristi-neagu** [comment]
You have to import mdfreader, not mdf4reader.

**Comment by Nordlxnder** [comment]
Hi cristi-neagu,

Thank you for your prompt reply.

Now I use :
from mdfreader import mdf
