### ISSUE TITLE
Export to xlsx: Columns/Signal names missing,  repeating columns taken only once

### ISSUE THREAD

**Issue by livias** [ratal/mdfreader#134]
# Pyhton version 
Please write here the output of printing ``sys.version`` 3.6.3

# Platform information
Please write here the output of printing ``platform.platform()``

# Numpy version
Please write here the output of printing ``numpy.__version__``

# mdfreader version
Please write here the output of printing ``mdfreader.__version__`` current 4

# Description
Export to xlsx:  6 Columns/Signal names missing among which one related to timestamp.

**Comment by ratal** [comment]
I will refactor completely this excel export, very old and not efficient.
But just to confirm, I might have identified a bug, do you have invalid_bytes channels in your dataset after reading and before exporting ?

**Comment by ratal** [comment]
You can test with latest dev branch ?
