### ISSUE TITLE
Export to  csv doubles each line with an empty row

### ISSUE THREAD

**Issue by livias** [ratal/mdfreader#135]
# Pyhton version 
Please write here the output of printing ``sys.version``

# Platform information
Please write here the output of printing ``platform.platform()``

# Numpy version
Please write here the output of printing ``numpy.__version__``

# mdfreader version
Please write here the output of printing ``mdfreader.__version__``

# Description
Please describe the issue here and eventually script used to use mdfreader

Also mentionning version of mdf file will be helpfull (using mdfvalidator or mdfreader if functionnal for reading)

print of issue related variables at the errors location and eventually mdfvalidator screenshots can help troubleshooting complicated issues

**Comment by cristi-neagu** [comment]
First of, the template is there for a reason. Please use it as much as possible.

Secondly, to fix this, [this line](https://github.com/ratal/mdfreader/blob/bcf93307170ce6e2b4dba33a2c15b7240567d89c/mdfreader/mdfreader.py#L753) from `mdfreader.py` needs to change to this:

`                f = open(filename, "wt", encoding=encoding, newline='')`

**Comment by livias** [comment]
Thank you.

**Comment by ecalpy** [comment]
Hello - I'm having the same issue (my .csv export files have empty rows between data- and I'd like to remove that).  I tried adding the "newline='' " into the open function, but it does not change anything.  What else could I be doing wrong?

Also just wondering what the background of why there's empty rows on the exports?  Readability?

Many thanks!!
-ecalpy

**Comment by ecalpy** [comment]
> First of, the template is there for a reason. Please use it as much as possible.
> 
> Secondly, to fix this, [this line](https://github.com/ratal/mdfreader/blob/bcf93307170ce6e2b4dba33a2c15b7240567d89c/mdfreader/mdfreader.py#L753) from `mdfreader.py` needs to change to this:
> 
> ` f = open(filename, "wt", encoding=encoding, newline='')`

Hello- following up that this suggestion did not help!
