### ISSUE TITLE
AttributeError when overwriting (read/write) with write3

### ISSUE THREAD

**Issue by skidzo** [ratal/mdfreader#138]
# Pyhton version 
'3.6.3 |Anaconda custom (64-bit)| (default, Nov  3 2017, 19:19:16) \n[GCC 7.2.0]'

# Platform information
'Linux-4.13.0-37-generic-x86_64-with-debian-stretch-sid'

# Numpy version
'1.14.1'

# mdfreader version
'2.7.4'

# Description
trying to overwrite the file read

# MDFVersionNumber
320

  File "/home/user/anaconda3/lib/python3.6/site-packages/mdfreader/mdfreader.py", line 430, in write
    self.write3(fileName=fileName)
  File "/home/user/anaconda3/lib/python3.6/site-packages/mdfreader/mdf3reader.py", line 1215, in write3
    temp = ncode(temp, encoding='latin1', errors='replace')
  File "/home/user/anaconda3/lib/python3.6/site-packages/numpy/core/defchararray.py", line 540, in encode
    _vec_string(a, object_, 'encode', _clean_args(encoding, errors)))
AttributeError: type object 'bytes' has no attribute 'encode'

**Comment by ratal** [comment]
Hi, thanks for reporting,
maybe you can try directly the line just before
data.dtype.kind == 'U'
'S' might not make sense for python 3.x, means byte.

**Comment by skidzo** [comment]
Hi Aymeric,

I inserted after line:
`data = self.getChannelData(channel)  # channel data`

your suggestion:
`data.dtype.kind == 'U'`

with no effect, same error

**Comment by skidzo** [comment]
and interesting, the file i read contains additionally in file_metadata the keys: 'comment', 'time' and 'date', If I read the write3 function correctly it only writes 'author', 'organisation', 'project' and 'subject' from file_metadata.

**Comment by ratal** [comment]
Probably the following is more correct:
```
if PythonVersion >= 3:
          if data.dtype.kind == 'S':
temp = ncode(temp, encoding='latin1', errors='replace')
         elif data.dtype.kind == 'U':
temp = ncode(temp, encoding='utf-8', errors='replace')
```

This is all about text coding, so I do not this the relation with floating type.

Regarding the organisation, project subject, etc. these are by default values put in general comments by Inca. I guess your 'comment', 'time' and 'date' are also specific to your data logger, which is ?
You can modify for your own needs the method add_metadata that is in mdf.py

By the way, any modification you do can be proposed by a pull request if you want it in mdfreader

**Comment by skidzo** [comment]
i made a quick test and can confirm that this is more correct. I am aware of the add_metadata method. Our file was produced with CANape I checked with MDF Versions 3.2 and 3.3

**Comment by ratal** [comment]
Date, Time, Author, Organization, Project, Subject are fields of HDBlock in mdf3.x. It contains also a link to a TXBlock containing comment.
For Inca, Project, Organization, etc. are actually not in the HD Fields (fixed size) but in the TXBlock Comment text (variable size).
Is your issue solved ? If yes close, otherwise please explain what you expect at this point.
