### ISSUE TITLE
Error when trying to install version 0.1.9 under Windows/Anaconda

### ISSUE THREAD

**Issue by leiber83** [ratal/mdfreader#14]
Hi,
I was trying to install the new version (0.1.9.1) of mdfreader. Therefore I installed cython and its dependencies for Windows (https://github.com/cython/cython/wiki/CythonExtensionsOnWindows). Unfortunately, the package installation exited with the following error:

building 'mdfreader.dataRead' extension
C:\Users\zzz\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Anaconda\include" "-IC:\Program Files\Anaconda\PC" /Tcmdfreader/dataRead.c /Fobuild\temp.win-amd64-2.7\Release\mdfreader/dataRead.obj
dataRead.c
mdfreader/dataRead.c(250) : fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory
error: command 'C:\\Users\\zzz\\AppData\\Local\\Programs\\Common\\Microsoft\\
Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

Is there a special numpy-package, that I need to install first?

EDIT:
I solved the issue by importing numpy in setup.py and adding "include_dirs=[numpy.get_include()]"  in line 104 after "ext_modules=cythonize('mdfreader/dataRead.pyx'),"

**Comment by ratal** [comment]
Thanks Leiber for the update, I will include it in git.
