### ISSUE TITLE
No meta data in event block available

### ISSUE THREAD

**Issue by ro-gro** [ratal/mdfreader#140]
# Pyhton version 
3.4.7

# Platform information
Windows-10-10.0.16299

# Numpy version
1.13.3

# mdfreader version
2.7.4

# Description
I cannot access meta data from meta data block within an event data block by using mdfreader.mdfinfo("filename.mf4")
The mf4 file is written by our own software, but I can see all the expected meta data in the Vector mdf validator.

After debugging the mdfinfo4.py file I might have found the problem in the CommentBlock class. All the needed data is in the xml_tree variable (line 398), but it seems, that in an event data block, the meta data block does not have an "MDType" (line 404). -> CommentBlock  object not filled with this data.

Additionally, I find it a little bit confusing, that all the base keys from mdfreader.mdfinfo dict have been renamed (CNBlock to CN aso.) but not the EVBlock.

**Comment by ratal** [comment]
Hi,
I changed in dev branch:
'EVBlock' -> 'EV', indeed more consistent.
added MDType = 'EV'
You can check if you have what you want

**Comment by ro-gro** [comment]
Hi,
I tested it with the latest dev branch and it works as expected now.
Thank you!
