### ISSUE TITLE
Unable to parse CE blocks in MDF 3 files with ext. type=19

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#141]
Hi,

line 638 in mdfinfo3.py:
`temp['name'] = temp['name'].rstrip(b'\x00').decode('latin1', 'replace')`
has to be replaced with:
`temp['message'] = temp['message'].rstrip(b'\x00').decode('latin1', 'replace')`

**Comment by ratal** [comment]
Thanks, I never could confirm it !
