### ISSUE TITLE
Raw values are wrong if bit count is not a multiple of 8 (MDF 3 files)

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#142]
If I read the values of a channel whose bit count is not a multiple of 8, then the returened values are wrong.

Example:
![image](https://user-images.githubusercontent.com/7522976/37899442-d2945c90-30eb-11e8-8e34-152fc0d25cac.png)

The returned sequence is: [4160.749566, 4160.749566, 4160.749566, ...]
The expected sequence is: [134,217726, 134,217726, 134,217726, ...]

* pyhton version ``3.6.4``
* platform information ``Windows-7-6.1.7601-SP1``
* numpy version ``1.14.0``
* mdfreader version ``2.7.5``
* mdf file version ``3.10`` - see attached [issue_142.zip](https://github.com/ratal/mdfreader/files/1848320/issue_142.zip)

**Comment by ratal** [comment]
You can check in latest dev branch, I modified dataRead.pyx, there was a bug in it.
--> you will need to recompile it

**Comment by ginseil** [comment]
Works like a charm. Thank you! :)
