### ISSUE TITLE
mdfreader is returning error after upgrade to 2.7.5 when reading mdf files

### ISSUE THREAD

**Issue by Mark584** [ratal/mdfreader#143]
# Pyhton version 
3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

# Platform information
Windows-10-10.0.15063-SP0

# Numpy version
1.14.2

# mdfreader version
2.7.5

# Description

After upgrading from mdfreader 2.7.4 to 2.7.5, it won't read my mdf files anymore.
Executing the following command:

`yop = mdfreader.mdf('MDF-File.mdf')`

will return:

```
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\mdfreader\mdfinfo3.py", line 638, in read_ce_block
    temp['name'] = temp['name'].rstrip(b'\x00').decode('latin1', 'replace')

KeyError: 'name'
```

Before upgrading mdfreader, it worked with my mdf-files. How can I solve this problem?

**Comment by Mark584** [comment]
Thanks for your response!

I changed this line, but now I'm getting a different error somehow:


```
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\lib\site-packages\mdfreader\mdfinfo3.py", line 99, in __init__
    self.filterChannelNames = filterChannelNames

TypeError: descriptor 'filterChannelNames' for 'info3' objects doesn't apply to 'info3' object
```

**Comment by ratal** [comment]
I cannot understand, there should be below line
__slots__ = ['fileName', 'fid', 'filterChannelNames']
under info3 declaration, so this TypeError does not make sense. Did you change anything ?

**Comment by Brausepaul** [comment]
I can confirm the original issue but not the following problem mentioned.

**Comment by Brausepaul** [comment]
Sorry, after re-reading my previous comment I think I was unclear. I did have the same issue with 2.7.5 but replacing the line mentioned fixed it for me.

**Comment by ratal** [comment]
long time no feedback, seems fixed, closing
