### ISSUE TITLE
TypeError in mdf3reader.py 

### ISSUE THREAD

**Issue by StefScho** [ratal/mdfreader#144]
In the current dev branch lines 553 in mdf3reader.py leads to a TypeError.
https://github.com/ratal/mdfreader/blob/9c827c62b4aa085126e92147dbf5b937b6352b8d/mdfreader/mdf3reader.py#L553

sys.exc_info() returns a tuple, which leads to the following error

> TypeError     Traceback (most recent call last)
> ---->  warn('Unexpected error:', sys.exc_info())
> TypeError: category must be a Warning subclass, not 'tuple'

**Comment by ratal** [comment]
Hi, you are right, probably forgot it when I converted from print() to warn().
Probably below should better work ?
`warn('Unexpected error: {}'.format(exc_info()))`

**Comment by ratal** [comment]
Should have fixed your issue
