### ISSUE TITLE
IndexError 13

### ISSUE THREAD

**Issue by Taha2312** [ratal/mdfreader#145]
# Pyhton version 
Please write here the output of printing ``sys.version``3.6.4

# Platform information
Please write here the output of printing ``platform.platform()``

# Numpy version
Please write here the output of printing ``numpy.__version__``

# mdfreader version
Please write here the output of printing ``mdfreader.__version__``0.2.2

# Description
IndexError 13 appearing after running following code:

import mdfreader
yop= mdfreader.mdf(r'C:\Users\User\Desktop\abc.mf4')

  File "src/lxml/objectify.pyx", line 308, in lxml.objectify.ObjectifiedElement.__getitem__ (src\lxml\objectify.c:5418)
IndexError: 13

I also tried the following:

yop = mdfreader.mdf4reader.mdf4(...) but it didnt work.

Can you help me?

**Comment by ratal** [comment]
Hi,
You use a very old version of mdfreader. 0.2.2 is the beginning of mdf4 support.
I would strongly advise you to update to latest version.

**Comment by Taha2312** [comment]
Hello,


I updated the mdfreader to the Version 2.7.5. But still I receive the same problem: IndexError 13



________________________________
Von: Aymeric Rateau <notifications@github.com>
Gesendet: Samstag, 14. April 2018 22:04
An: ratal/mdfreader
Cc: Taha2312; Author
Betreff: Re: [ratal/mdfreader] IndexError 13 (#145)


Hi,
You use a very old version of mdfreader. 0.2.2 is the beginning of mdf4 support.
I would strongly advise you to update to latest version.

**Comment by ratal** [comment]
Hi,
It seems this is an error from lxml module.
Probably a weird/malformed xml. 2 directions:
- confirm version of lxml and eventually update it to latest version.
- identify faulty xml and develop solution. With latest mdfreader vesion, all objectify should be within a try: except and only warn you if xml reading has an issue. Are you sure latest mdfreader version is active in your session ?

**Comment by ratal** [comment]
no news since a while, closing but you can reopen if you could dig into this lxml issue
