### ISSUE TITLE
channel values are wrong

### ISSUE THREAD

**Issue by ginseil** [ratal/mdfreader#151]
# Python version
3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:23:52) [MSC v.1900 32 bit (Intel)]

# Platform information
Windows-10-10.0.16299-SP0

# Numpy version
1.14.3

# mdfreader version
2.7.8 (current master branch)

# Description
Hi, the mdfreader returns wrong values for any channel of the attached mdf file (v3.10) [issue.zip](https://github.com/ratal/mdfreader/files/2344912/issue.zip). So for example in case of channel 'Signal3' the returned values are: [0, 75.5, 75.5, ...]. The expected values are: [0, 89, 89, ...].

The expected reults for each channel:
Signal1:
![signal1](https://user-images.githubusercontent.com/7522976/44977591-bb61ab80-af68-11e8-9d49-6636473220f3.PNG)

Signal2:
![signal2](https://user-images.githubusercontent.com/7522976/44977594-bb61ab80-af68-11e8-9f48-b11c91097c81.PNG)

Signal3:
![signal3](https://user-images.githubusercontent.com/7522976/44977589-bac91500-af68-11e8-9a6b-cae4c44dc718.PNG)

Signal4:
![signal4](https://user-images.githubusercontent.com/7522976/44977590-bac91500-af68-11e8-99ae-5e17d0982a37.PNG)

**Comment by ratal** [comment]
Thanks Ginseil, it's a good one, tricky data layout, working on how to improve situation

**Comment by ginseil** [comment]
That's great, I'll dig into it on monday :)

Thank you!

**Comment by ginseil** [comment]
Works like a charm.
