### ISSUE TITLE
No string representation of mdfreader object

### ISSUE THREAD

**Issue by proedig** [ratal/mdfreader#155]
Python version
'3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'

Platform information
'Windows-10-10.0.14393-SP0'

Numpy version
'1.14.3'

mdfreader version
mdfreader 2.7.8
Tree mdfreader-0895a77c733f0b9ddf167dfd3cbceb24a66ad732

Description

Hi! I noticed that there is no string representation of the generated mdfreaderobject:

`yop = mdfreader.mdf(file)`
`print(yop)`

results in `TypeError: __str__ returned non-string (type list)`

I also tried just `yop` without print(). Results in no output.

**Comment by ratal** [comment]
mdf (mdfreader.py) inherits of mdf3,mdf4 (mdf3reader.py,mdf4reader.py), which itself inherits from mdf_skeleton (mdf.py) that includes __str__
when I use ipython, I can get a print of yop.
However, I could reproduce your issue with print(yop).
__str__ ouput nested list. ipython print does not complain but print() gives same error as yours -> I corrected in dev branch, should be fixed for you.
You can customise according to your needs __str__, do not hesitate to propose modifications.
