### ISSUE TITLE
Merge two files

### ISSUE THREAD

**Issue by coppolajj** [ratal/mdfreader#157]
# Python version
Please write here the output of printing ``sys.version``
'3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]'

# Platform information
Please write here the output of printing ``platform.platform()``
'Windows-7-6.1.7601-SP1'

# Numpy version
Please write here the output of printing ``numpy.__version__``
'1.15.1'

# mdfreader version
Please write here the output of printing ``mdfreader.__version__``
'2.7.8'

# Description
trying to merge two files with:
```
yop=mdfreader.mdf(mdfFile)
yop.resample(0.1)
yop2=mdfreader.mdf(mdfFile2)
yop2.resample(0.1)
yop.merge_mdf(yop2)
```
but get this error:
`AttributeError: 'mdf' object has no attribute 'merge_mdf'`

# MDF Version
``yop.MDFVersionNumber``
410
``yop2.MDFVersionNumber``
410

**Comment by ratal** [comment]
Ok, I close this ticket then, thanks for informing.
