### ISSUE TITLE
numpy import error in 3.0.0 if no cython

### ISSUE THREAD

**Issue by DocBO** [ratal/mdfreader#158]
# Python version
3.7.1

# Platform information
Linux-4.15.0-42-generic-x86_64-with-debian-buster-sid

# Numpy version
1.15.4

# mdfreader version
3.0.0

# Description
The setup.py is not working correctly if cython is not installed. You get an numpy error (which is not defined in that case since it is never imported). 

If cython is installed by hand previously, everything works fine. So either include cython into your depencies or import numpy on another place too.

**Comment by denizsivas** [comment]
Same here.

**Comment by ratal** [comment]
Hi,
there was a remaining `include_dirs=[numpy.get_include()]` in case extension could not be compiled, removed and this error should not happen.
If you have occasion can you confirm ?

**Comment by ratal** [comment]
Seems it is fixed, thanks for reporting, closing issue.
