### ISSUE TITLE
Concatenating Multiple Dataframes

### ISSUE THREAD

**Issue by msnir009** [ratal/mdfreader#159]
# Python version
3.7.1

# Platform information
'Windows-10-10.0.16299-SP0'

# Numpy version
1.16.2

# mdfreader version
'3.0'

# Description
I have mdf files that contains recordings in different timestamp frequencies. When I used the convert_to_pandas() function, it creates multiple dataframes according to the different recording frequencies. How do I then concatenate these dataframes so that it appears in one big table instead? Thank you.

**Comment by ratal** [comment]
Hi
This default behavior avoids loosing information or inflating memory use unintended.
You could resample the pandas frame using .resample and .join
Otherwise, you could resample using mdfreader before the convert to pandas.

**Comment by ratal** [comment]
I guess it helped.
If still problematic feel free to reopen this issue
