### ISSUE TITLE
channel values are wrong between some range and rest are correct

### ISSUE THREAD

**Issue by az299260** [ratal/mdfreader#160]
# Python version
'3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'

# Platform information
Windows-7-6.1.7601-SP1

# Numpy version
1.15.4

# mdfreader version
3.0

# Description
I have read an mdf file using mdfreader. some signals are populating wrong values between some range

Also when i read the same file using matlab the data is coming correct without any calculations
When read usig asammdf library the output is same as matlab

# Code
yop = mdfreader.Mdf(filename)
signame = yop.get_channel_data()

Below matlab values are expected in pythob, but i'm getting the wrong values in python.
values below 0 and values in between some particular range are coming wrong

Observed output
Python | Matlab
0.256256 | 0.256256
0.494026 | 0.494026
0.255942 | 0.255942
0.006016 | 0.006016
499.33 | -0.24393
510.774 | -1.22582
510.018 | -1.9819
509.512 | -2.48834
31.2382 | 31.23815
31.7379 | 31.73793
469.335 | 31.99405
480.244 | 32.24376
480.738 | 96.73828
480.262 | 96.26209
104.719 | 95.76166
95.2623 | 95.26225
94.7616 | 94.76159
94.75 | 94.75
94.2619 | 94.26194

**Comment by az299260** [comment]
Hi @aymeric

Waiting for your reply

**Comment by az299260** [comment]
Hi @Aymeric

Still waiting for your reply

**Comment by ratal** [comment]
Hi, sorry for the delay, I was in vacation.
Seems the channel is considered wrongly as signed but I need more information to troubleshoot.
were you able to compile the cython module ?
Can you show the CNBlock of the channel ?
Best would actually if you can share your file ?

**Comment by az299260** [comment]
Hi,
Sorry i can't share the file. 
not sure about the cython and CNBlock, Could you let me know how to check that, so i can provide you the details you require

**Comment by ratal** [comment]
Hi,
you can take reference from issue #59 or #149

**Comment by az299260** [comment]
[cnblock](https://user-images.githubusercontent.com/49338300/56260684-c59a7980-60f5-11e9-89ce-ae733d398469.PNG)

Hi, please find the CNblock image.
still not sure about the cython module

**Comment by ratal** [comment]
Hi,
Your file is mdf3.x, so the reading is happening in mdf3reader.py
If you want to confirm is dataRead (the cython module) is correctly compiled/installed, you can try using a breakpoint around line 520 and the try: statement.
Do you have a warning when executing saying : 'dataRead crashed..' ?
I see this is a motorola ending type in 3 bytes. the fallback in case dataRead is missing is basic and most probably your channel is read on 4 bytes and the 3rd byte is not masked, you might be reading 1 channel and partially another.

**Comment by ratal** [comment]
Normally, there is the attribute .bit_masking_needed that should trigger the masking of the 4th byte.
Can you check for this channel what are the values of this attribute and also .embedding_channel_bitOffset ?

**Comment by az299260** [comment]
yes i did get the warning. also i have mailed you a sample file. please have a look

**Comment by ratal** [comment]
Hi,
I strongly advise you then to make work the cython dataRead module.
Normally, it should be included in the module wheel you installed from pip, can you check ?
Also, if it would not work for some reasons, you should compile it with cython but on windows it is not that easy (you need the correct developer environment for your versions of windows and python)
I can also try to fix the issue of the fallback code with your file but I even checked my spam folder, I did not receive it. Can you resend to aymeric.rateau@gmail.com ?

**Comment by az299260** [comment]
Hi, I have sent you mail again, could you please check

**Comment by ratal** [comment]
Are you sure you get a warning for dataRead ?
I actually did not find any issue without dataRead but potentially a bug with byte swapping in dataRead.

**Comment by ratal** [comment]
I fixed a bug in dataRead in dev branch, you could give a try.

**Comment by az299260** [comment]
Hi,
Sorry for late reply, yeah the code is working fine now, could you brief the details of bug

**Comment by ratal** [comment]
I released version 3.1 fixing a bug with big endian data (9 = Unsign_Motorola) in dataRead, the compiled extension --> did you try it ? (It fixed similar error of your first screenshot) Do you still have warning 'dataRead crashed..'  ?

With the file I received from you, I could not reproduce on my linux and win10 PCs your issue trying the 3 ways of parsing data (fromstring, dataRead or fallback). By default mdfreader is not using dataRead or its fallback but directly numpy.fromstring() that should properly handle endians (To force using dataRead, you can add for instance a list of channels in arguments ( ,channel_list=['channel1', 'channel2', ...]), maybe try it). Also, my configurations are relatively updated (1.16.2) and I noticed you use numpy version 1.15.4 and some work has been done with ctypes and endianess, maybe facing an unknown bug from numpy -> so if you can update easily, you can try it (I feel unlikely though).
Also how do you use mdfreader ? Can you share the command lines ? Can you check by debbuging in which part of read_sorted_record() the data are parsed ?
For the last screenshot compared to first one, channel is using 20 bit and not 12, so reading on 3 or 4 bytes It is possible that actually other channels are included into those 3 or 4 bytes, creating changing values while it should not (or simply bad endianess handling). I guess this is second channel (number of first bit 64, most likely time) but can you share next channel screenshot if existing to check if it is any embedded ? --> mdfreader should detect it and force dataRead use.

**Comment by az299260** [comment]
for the first screen shot the error has been fixed, and i don't have any warning
 i have attached the next channel for the second screenshot, 

![next cnblock](https://user-images.githubusercontent.com/49338300/57118932-195ac300-6d84-11e9-9f69-6f612c39b489.PNG)

**Comment by az299260** [comment]
Below is the code i'm using to fetch data. and after getting Signal2 data the values are mismatched as i mentioned in above comments

```
import mdfreader
filename = "sample.mdf"
myobj = mdfreader.Mdf(filename)
tem = myobj.get('signal1')
sample_by = tem["master"]
myobj.resample(master_channel=sample_by)
Signal2 = yop.get_channel_data('signal2')
```

**Comment by ratal** [comment]
I cannot reproduce your issue with the file and the script you shared.

**Comment by az299260** [comment]
yeah sorry, thats because the signal i'm talking about in not in that file. I have sent a new file with the signal. along with expected and observed values

**Comment by az299260** [comment]
yeah sorry, thats because the signal i'm talking about in not in that file. Im sending a new file with the signal. along with expected and observed values

**Comment by ratal** [comment]
Hi,
Did you reply to the github notification email ? --> you sent twice your answer ?
Can you send by email your file like you did last time ?

**Comment by ratal** [comment]
Thanks for the file, I could identify the bug.
You can already try it with the latest dev branch if you are interested

**Comment by az299260** [comment]
sorry for late reply. Just checked the code, its working fine, i can read the correct values now . does this signal too has the same reason as other signal for reading wrong data?

**Comment by ratal** [comment]
Good news :)
The bug was related to all signals that use non aligned byte records with dataRead. Not aligned byte means for instance:
- on 3 bytes ; 17 to 24 bits was read with 4 bytes instead (your last example file)
- and between 33 to 56 bits was read with 8 bytes instead of 5, 6 or 7 bytes.

It is one reason of existence of dataRead cython module ; it is complicated to handle efficiently these kinds of record structures with python or numpy.fromstring. But some recorders use this to optimise the size of mdf file.
dataRead was coded to properly handle non aligned bytes but was receiving as argument a number of bytes calculated considering aligned bytes instead of non aligned bytes.

You first file contained signal on 12bits but big endian. No issue with the alignment but the byte swapping from big endian to little endian in dataRead was wrong.
