### ISSUE TITLE
[Feature Request] Keep Original signalName in Result Dictionary

### ISSUE THREAD

**Issue by bbto89** [ratal/mdfreader#161]
# Python version
Python 3.5.2

# Platform information
'Linux-4.9.87-linuxkit-aufs-x86_64-with-centos-7.4.1708-Core'

# Numpy version
'1.14.2'

# mdfreader version
'2.7.6'

# Description
* Current Behaviour:
When we use the mdfreader to read mdf3 or mdf4 files, duplicate signal names do not keep their original signal name. Yet, all duplicate signal names are concatenated with an additional identifier like "_285".

* Problem:
After we read and converted the mdf files to parquet, we cannot distinguish between those duplicate signal names.

* Feature Request:
In mdfinfo3/4.py we would like to have an addtional key which represents the original signal name in the mdf file, in addition to the existing "signalName" key.

**Comment by ratal** [comment]
Ok, I can try to propose you something.
However, it would be better to understand your real problem you want to solve, to make sure it will definitely help you.
Why only mdfinfo3/4 ?
Don't you want to have the original name kept in mdfreader also ?
By the way, self['CN'][dg][cg][cn]['orig_name']  is already existing in mdfinfo4.

**Comment by ratal** [comment]
I added a key in mdfinfo3 'orig_name' same as mdfinfo4 in dev branch.
For info, in this branch I added a new export_to_parquet method using pandas. Coudl be interesting to

**Comment by bbto89** [comment]
Thanks! Worked fine for mdf3 files.
