### ISSUE TITLE
Feature Request: Make new MDF. Used for xlsx to MDF

### ISSUE THREAD

**Issue by Mark0ne** [ratal/mdfreader#162]
# Python version
3.7.2

# Description
Is this already possible?  If not, is it a relatively easy addition?  I'd like to be able to enode a new MDF file and populate it with signals from another source (in my case, Excel).

Thanks

**Comment by ratal** [comment]
Theoritically, possible. But maybe not so well documented. How I would see it:
Mostly use MdfSkeleton class. After import of mdfreader and your data (in pandas or openpyxl ?)
`yop=mdfreader.Mdf()`
`yop.add_channel(channel_name, data, master_channel, master_type, unit='lumen', description='what you want')  # many times as needed`
`yop.write('filename') # change version with yop.MDFVersionNumber or specifically use write3/4()`
Tell if you find issues

**Comment by ratal** [comment]
Seems it went well ? closing considering the time

**Comment by Mark0ne** [comment]
Yes, thanks, it worked. Many thanks for the suggestion
