### ISSUE TITLE
mdf.write3() omits all channel units

### ISSUE THREAD

**Issue by arne7morgen** [ratal/mdfreader#173]
# Python version
3.7.3

# Platform information
Windows-10-10.0.17763-SP0

# Numpy version
1.16.3

# mdfreader version
3.2

# Description
When writing a Mdf3 file with `mdf.write3("name.dat")` and reloading the Mdf again with `Mdf("name.dat")` the channels of the Mdf have no units.

The bug is a wrong parenthesis and is swallowed by _The Most Diabolical Python Antipattern_ (https://realpython.com/the-most-diabolical-python-antipattern/)

**Comment by arne7morgen** [comment]
Pullrequest is here: #174

**Comment by ratal** [comment]
merged.
Thanks for the pull request !
