### ISSUE TITLE
how to get the name and numbers of the groups in MF4?

### ISSUE THREAD

**Issue by AndyYangjd** [ratal/mdfreader#175]
Hi, 

Thanks for your mdfreader module.
But i get a little confused about where can i get the group's info, such as the length, names.
In fact, can the user get some functions, ex. get_NGroups(), getGroupName(group_id)?

Have a nice day!

**Comment by ratal** [comment]
Hi,
There are several ways of getting this information.
1. with mdfinfo class, it is reading only metadata of MDF file
2. after reading a file and its data, for each channel you have a 'id' key containing a tuple of ((data group number, channel group number, channel number), (channel name, channel source, channel path), (group name, group source, group path))
3. the attribute masterChannelList is representing the structure of the mdf with one master key per group having a value list of channel.

**Comment by AndyYangjd** [comment]
Hi,
I get it.

Thanks for your reply.
