### ISSUE TITLE
Wrong master channel allocation while exporting to HDF5

### ISSUE THREAD

**Issue by dezire99** [ratal/mdfreader#18]
While making use of exportToHDF(), I have seen that the signals get allocated to wrong master channels. I have looked into the function exportToHDF() and managed to add a couple of lines of code with an 'elif' condition, thereby fixing the problem. However, I have tested the fix on only one mdf file, and am not sure if it solves the bug for all cases. I have put a screenshot below from the method 'exportToHDF' in mdfreader.py.

![image](https://cloud.githubusercontent.com/assets/16312143/11825233/1bdb083e-a37e-11e5-9bb0-fa509e589367.png)

**Comment by ratal** [comment]
Thanks, no errors from my tests, I implemented your modification in master.
