### ISSUE TITLE
convert unsorted mdf file

### ISSUE THREAD

**Issue by z1987124** [ratal/mdfreader#183]
How can  I convert unsorted mdf file to sorted file ,there mdfreader have this method ?

**Comment by ratal** [comment]
yes, relatively easy:
```
yop=mdfreader.Mdf('unsortedfile.mdf')
yop.write()
```
It will write it in sorted (unsorted writing does not exist in mdfreader and does not make sense anyway, your computer is not a logger that is resources constrained for writing mdf files)
You could also use parameter column_oriented=True (not yet default, new) that will write sorted but one channel per data block, speeding up reading by computer.
