### ISSUE TITLE
Could not parse CG block names tag warn

### ISSUE THREAD

**Issue by AndyYangjd** [ratal/mdfreader#185]
# Python version
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]

# Platform information
Windows-10-10.0.17763-SP0

# Numpy version
1.17.2

# mdfreader version
4.0

# Description
After a MF4 file is imported, a warn print in the screen below.
> mdfreader\mdfinfo4.py:596: UserWarning: Could not parse CG block names tag
  warn('Could not parse CG block names tag')

What does that mean?

Many thanks for mdfreader. It's amzing!

**Comment by ratal** [comment]
Hi Andy,
It means mdfreader cannot properly read some xml metadata. It happens with some loggers, the xml is not always respecting the standard schema. It is just a warning, and the CGBlock does generally contain no so important metadata, so no worry.

**Comment by AndyYangjd** [comment]
Hi ratal,
Thanks for your reply.
