### ISSUE TITLE
Could not keep the original  data format with 'mdfreader.write'

### ISSUE THREAD

**Issue by likunjay1986** [ratal/mdfreader#186]
# Python version
python 3.7.0.64

# Platform information
Windows7

# Numpy version
1.18.5

# mdfreader version
3.3

# Description
When working with the 'dat' format data recorded by INCA, I find that part of  information is lost if I use the _mdfreader_ method _'write'_.
For example:
1. Information of  _'unit'_ are all lost
2. The _'Bool'__ data is converted to _'int'_

**Comment by ratal** [comment]
a boolean in a PC is an integer of 8bits, same. mdfreader's write method does not embed bits in bytes, so will take a bit more space but will be quicker to read. It is also more complicated to code the writer, so did not do.
Regarding the unit, write() method should write units. Could be a bug. It is around line 1339 of mdf3reader.py, you could debug there and understand what is happening but first thing to check is if you can read the units before trying to write them.

**Comment by ratal** [comment]
No feedback since almost 6 months, closing but do not hesitate to reopen if needed
