### ISSUE TITLE
Can we specify interpolation method while resampling?

### ISSUE THREAD

**Issue by SanjayBalaji** [ratal/mdfreader#191]
# Python version
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

# Platform information
Windows-10-10.0.17763-SP0

# Numpy version
1.18.2

# mdfreader version
4.1

# Description
Similar to that of interp1d in scipy, is there a way we specify the type of interpolation ('linear', 'quadratic', 'previous', 'next', etc..) being done during resampling of data?
This is because, some channels record data only when there is a change( Eg. [ 7.00073242, 10.00061035, 19.99969482, 0.00061035, 19.99969482, 10.00061035, 19.99969482, 10.00061035, 19.99969482, 10.00061035, 10.00061035] ), but when we resampling, it interpolates linearly instead of interpolating in "next" method.

Thank you!

**Comment by ratal** [comment]
Hi,
Actually, interp() is used only for floating data. For integer or other types, the next data ('right') is taken.
You can have a look at the method resample() in mdfreader.py, around line 702
For the moment, interp from numpy is used. However, I could add condition if interpolation is given to use interp1D from scipy instead. But I guess you want to force next option even for floating ?

**Comment by SanjayBalaji** [comment]
@ratal Hi,
I added this code and it worked very well as expected! Thank you very much for taking your time to solve this problem!
