### ISSUE TITLE
export to csv adding an extra line

### ISSUE THREAD

**Issue by medis8731** [ratal/mdfreader#199]
# Python version
Please write here the output of printing ``sys.version``

# Platform information
Please write here the output of printing ``platform.platform()``

# Numpy version
Please write here the output of printing ``numpy.__version__``

# mdfreader version
Please write here the output of printing ``mdfreader.__version__``

# Description
Im trying to export an mdf file into a CSV. I tried exporting it with the mdfreader. but for some reason I'm getting an extra line in the beginning of the file (s,,,,). I don't understand why this problem is rising. I would appreciate any help. thanks!
I've tried changing the open file in the mdf reader but it hasn't changed anything. 
<img width="642" alt="Screen Shot 2021-07-01 at 6 35 34 PM" src="https://user-images.githubusercontent.com/56053205/124200501-21653900-da9b-11eb-98fc-bf0388d18aa5.png">
<img width="412" alt="Screen Shot 2021-07-01 at 6 34 44 PM" src="https://user-images.githubusercontent.com/56053205/124200454-05fa2e00-da9b-11eb-9146-2af2e3cf3dda.png">
<img width="697" alt="Screen Shot 2021-07-01 at 6 35 03 PM" src="https://user-images.githubusercontent.com/56053205/124200473-0eeaff80-da9b-11eb-9b81-f417a041fbfc.png">

**Comment by ratal** [comment]
This line is meant for units, time's unit is "s" (second), the other channel do not have units

**Comment by medis8731** [comment]
oh cool, thanks for the clarification!
