### ISSUE TITLE
Using / installing doesn't work anymore!?!

### ISSUE THREAD

**Issue by nexulm** [ratal/mdfreader#20]
Installing under cygwin (Windows7, 64bit OS) or Linux (Kubuntu 12.04) doesn't work and comes up with the following error:

$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build

**Comment by ratal** [comment]
What version of cython are you using ? I guess 0.15 for ubuntu 12.04
To use install mdfreader, you should use at least version>0.21
You can check with command "sudo pip show cython"
To upgrade, "sudo pip install --upgrade cython". You should also maybe at least upgrade numpy and pandas, depending of what you want to do. List of dependencies are in setup.py or README
You could also comment parts related to cython. It will only be necessary if you want to accelerate reading of file with not aligned bytes or read only specific channels for memory usage reduction (default is complete file loading in memory).

**Comment by ratal** [comment]
As no more feed back, issue closed
