### ISSUE TITLE
readmdf read network file

### ISSUE THREAD

**Issue by caijiya** [ratal/mdfreader#200]
Can I use mdfreader to read network files? At present, I write network files to temporary files first and then read them. However, during the operation of my web service (flask), file flow do not shutdown automatic, resulting in the report that the files are occupied when I finally delete the temporary files. How can I solve it

**Comment by ratal** [comment]
To my understanding, this kind of behavior could come from your Operating System which is protecting to read from a thread while writing at the same time the same file from another thread, it would lead to an undefined behavior. Your hard drive can hardly do it anyway. Ii seems you need to introduce sync mechanisms.
Your "network" file follows ASAM standard ? if yes, mdfreader should be able to read it.

**Comment by caijiya** [comment]
i am resoved it, because i find mdfreander can close stream rightly,thank you
