### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by gitdaemon** [ratal/mdfreader#26]
Hey i am getting following error when i try to import mdfreader

>>> import mdfreader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdfreader/__init__.py", line 25, in <module>
    from .mdf4reader import mdf4
  File "mdfreader/mdf4reader.py", line 38, in <module>
    from mdfreader.mdfinfo4 import info4, MDFBlock, ATBlock, IDBlock, HDBlock, DGBlock, CGBlock, CNBlock, MDFBlock, FHBlock, CommentBlock
  File "mdfreader/mdfreader.py", line 42, in <module>
    from mdf4reader import mdf4
ImportError: cannot import name mdf4

**Comment by gitdaemon** [comment]
@ratal am i missing anything here?

I cloned the repo and and did 

python setup.py install

then i tried to import mdfreader i am getting the above error.

**Comment by ratal** [comment]
Hi,
From which folder are importing mdfreader ? It should not be mdfreader/mdfreader

**Comment by ratal** [comment]
I just realized this happens with python2 and not python3. I do not know yet from where is coming from this regression.

**Comment by ratal** [comment]
This should be fixed with latest master
