### ISSUE TITLE
Dealing with very large files

### ISSUE THREAD

**Issue by pdrharris** [ratal/mdfreader#28]
Firstly, my sincerest apologies if this is not the place to post this - I am new to Github and wanted to raise a question but could not see where else to do it.
I am working with some very large MDF files, >1 or 2GB.  As such, my machine crashes when trying to convert them to CSV.  If I pull in a few channels, it works fine, so the software is installed correctly and working.  Is there any way to convert a portion of a file and so not to have to read in the whole thing?  I can use other CAN tools to do this but, if I could do all of my processing in Python, that would be amazing.
Many thanks for this software - it has been good to use so far.
Yours,
Peter

**Comment by ratal** [comment]
Dear,
I would say that without increasing your machine memory, you will have always difficulties to read big files.
But there are ways to optimise memory consumption:
1. you can use parameter convertAfterRead=False to have same memory use of your file (conversion to floating inflates memory use)
2. you can choose to only read a list of channels. To know the file list of channels, you can refer to issue #27 and then use the listchannel parameter
3. exporting to CSV is generally a bad idea for big files. You could export to HDF5 which is a good and widely used format (you can read it in Matlab for instance). But generally for whatever export, it is needed to copy some data so you also need memory margin.
Regards

**Comment by pdrharris** [comment]
Hello,
Thank you very much for getting back to me.  I am fairly new to all of this and appreciate your help.  
On the third point, the files are so big that it is not even getting as far as reading them in, even without trying to convert them and that is with convertAfterRead=False.  
So am I right in thinking that, if a CAN log was taken over 8 hours, there is no way of reading in only (say) the first hour or the second hour of data?  
If not, I will definitely look at limiting the channels that I read in or splitting the file using different software.
Thanks again,
Peter

**Comment by ratal** [comment]
Hi,
There is no functionality to have partial read of the data in mdfreader so I as you proposed, you should read a list of channels
Regards

**Comment by pdrharris** [comment]
Thank you very much for your help. I'll close the issue now but I'm very grateful.
Yours,
Peter
