### ISSUE TITLE
Error in setup.py

### ISSUE THREAD

**Issue by JosefLaumer** [ratal/mdfreader#30]
Hello,

got a problem when i start setup.py, seems to be with dataRead.pyx. I am using the Winpython Package.

![unbenannt](https://cloud.githubusercontent.com/assets/20229820/16586517/a7151eac-42c6-11e6-89a7-2156444b4b68.PNG)

**Comment by ratal** [comment]
Hi,
This seems weird at a first glance.
I only tested it on windows with Anaconda, I do not know winpython.
Which version are you using and most importantly, which version of cython is used ? It should be newer than 0.21
In setup.py there is a try: except which should install bitarray (low performance) instead of cython when failing. You could try to replace SystemExit maybe.
Aymeric

**Comment by JosefLaumer** [comment]
Hi,

i am back from vacation. I am trying Anaconda right now
(Anaconda3-4.1.1-Windows-x86_64.exe) but i think i am still too dumb to
call it with the right comands. Is there another help source except
readme.txt? Thanks in advance!

2016-07-05 16:39 GMT+02:00 Aymeric Rateau <notifications@github.com>:

> Hi,
> This seems weird at a first glance.
> I only tested it on windows with Anaconda, I do not know winpython.
> Which version are you using and most importantly, which version of cython
> is used ? It should be newer than 0.21
> In setup.py there is a try: except which should install bitarray (low
> performance) instead of cython when failing. You could try to replace
> SystemExit maybe.
> Aymeric
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ratal/mdfreader/issues/30#issuecomment-230497474>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATSuvMtlZndQ6OGVZTwdR9JxRJE9d5L-ks5qSmyPgaJpZM4JFITC>
> .
>



-- 


Mit freundlichen Grüßen
Josef Laumer

**Comment by ratal** [comment]
Yes there is documentation in docs folder, a pdf you could read in order to understand the internals of this module.
There are example, mostly made for ipython

**Comment by JosefLaumer** [comment]
The documenation helped a lot. I solved the problem with a raw string as
filepath (r"..."). But some commands in the pdf are wrong, like:
[image: Inline-Bild 1]
It should be yop.exportToMatlab(). But just for you as a hint. So far
everything is working.

But as i wanted to try the GUI i encountered another issue:
[image: Inline-Bild 2]
Maybe i am calling it wrong. Can you give me an example how to call the
GUI? I really would appreciate it.

2016-07-11 22:22 GMT+02:00 Aymeric Rateau <notifications@github.com>:

> Yes there is documentation in docs folder, a pdf you could read in order
> to understand the internals of this module.
> There are example, mostly made for ipython
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ratal/mdfreader/issues/30#issuecomment-231852865>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATSuvNyiYCGUDYTOrq6Fi1wsHWm0zxcLks5qUqYVgaJpZM4JFITC>
> .
>



-- 


Mit freundlichen Grüßen
Josef Laumer

**Comment by ratal** [comment]
The images do not appear, maybe a link issue ?
To launch the gui mdfconverter, from its folder, you should use python command, not ipython, like this:
python mdfconverter.py

**Comment by JosefLaumer** [comment]
Seems to be a link error. 

First picture:
![image](https://cloud.githubusercontent.com/assets/20229820/16846693/bd3d5f90-49ed-11e6-81ef-acc4a24440a7.png)

Second picture:
![image](https://cloud.githubusercontent.com/assets/20229820/16846715/cf8d53b2-49ed-11e6-9fcf-7e813026396f.png)

python mdfconverter.py is what i did as you can see. Between, thanks so far for your help!

**Comment by ratal** [comment]
In the setup.py script, there is entry_points that will create executable for whatever platform (normally).
Did you install mdfreader using pip (it should create executable) or by downloading the source code ?
If you did by downloading, I would advise to run command with admin rights: `python setup.py install`, or develop instead of install if you want to have code modifications effective.
You then have to simply launch command `mdfconverter` from a shell (forget about my previous comment).

**Comment by JosefLaumer** [comment]
This worked! Thanks a lot for your support and a great tool you created
there, please continue!

2016-07-14 20:20 GMT+02:00 Aymeric Rateau <notifications@github.com>:

> In the setup.py script, there is entry_points that will create executable
> for whatever platform (normally).
> Did you install mdfreader using pip (it should create executable) or by
> downloading the source code ?
> If you did by downloading, I would advise to run command with admin
> rights: python setup.py install, or develop instead of install if you
> want to have code modifications effective.
> You then have to simply launch command mdfconverter from a shell (forget
> about my previous comment).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ratal/mdfreader/issues/30#issuecomment-232748890>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATSuvAyBS35dgRe9X098qirY2pHlD8aPks5qVn3igaJpZM4JFITC>
> .
>



-- 


Mit freundlichen Grüßen
Josef Laumer

**Comment by ratal** [comment]
You're welcome !
