### ISSUE TITLE
Sampling Frequency Information

### ISSUE THREAD

**Issue by OnkarDeshpande** [ratal/mdfreader#31]
I was trying to go through the code and understand how exactly are you handling the channel data which are sampled at different frequencies. Are you up-sampling it or down-sampling it? 

Thanks in advance.

**Comment by ratal** [comment]
Mdfreader reads the raw data and loads it in memory, there are no resampling done during file reading.
You can up or down sample it by using method .resample() afterwards (in mdfreader.py, you can have a look)

**Comment by ratal** [comment]
I guess I answered your question.
