### ISSUE TITLE
Error while reading mdf files with field names containing colons

### ISSUE THREAD

**Issue by donvicario** [ratal/mdfreader#32]
Hello,

I want to read some MDF files with the mdfreader tool. My MDF files have some fields which are called "Dauermesung_1: Time", "Dauermessung_2: Time", etc. If I read these files with mdfreader.mdf() I get the error

ValueError: ':' is not an allowed character in buffer field names

Is there a chance to fix this?

Best regards, donvicario

**Comment by ratal** [comment]
Hi,
which version of mdf file are you trying to read ?
in mdfreader.py, there is a function called _convertMatlabName. It should remove problematic characters and could be reused in the code to solve your issue, for instance in mdf.py add_channel() method.

**Comment by ratal** [comment]
Do you still have this issue ? Critical ?
As no answer for a while, I close this issue, feel free to reopen it.

**Comment by tivoodoo** [comment]
Hi, I have the same issue reading a MDF 3.00 file right during the initialize phase
![2017-05-03 13_24_36-mdfreader_python_test](https://cloud.githubusercontent.com/assets/12232880/25658598/f8ce1e76-3003-11e7-9887-05a0ed8a6068.jpg)

How exactly should I use the function _convertMatlabName? 
As I understand, I should modify your code and call _convertMatlabName from add_channel() method. Is it correct? Unfortunately I'm new to Python and don't know how to modify the code correctly, can you please show me how?

Thank you a lot in advance.

**Comment by ratal** [comment]
_convertMatlabName is an example of function that is cleaning name from not allowed characters., it can be introduced in the code to avoid this issue but this is dirty patch.
':' character is allowed for a dict key.
But as I do not see where is this error in the code (your picture is not complete) and no complete information either from donvicario, I cannot troubleshot. Could you please send your snapshot again or inform the line number and in which file for the final error?

**Comment by tivoodoo** [comment]
Thank you a lot for your fast reply and also sorry for my late.
Here is the full trace:
![2017-05-09 10_16_22-mdfreader_python_test](https://cloud.githubusercontent.com/assets/12232880/25841533/bf7cd2ec-34a0-11e7-908b-e73478b39379.jpg)

**Comment by ratal** [comment]
Thanks for the update.
It is more clear now. Actually, recarray uses python identifiers, which has not allowed characters.
I implemented a new function in mdf.py module shared in all modules to declare only the recarray format.
--> it should solve your issue, please try.

**Comment by tivoodoo** [comment]
It worked! Thank you a lot!!!
