### ISSUE TITLE
'dict' object is not callable

### ISSUE THREAD

**Issue by blubbsy** [ratal/mdfreader#37]
Hi,
iam trying your cod example on amdf file i have and i cant figure out whats actually going wrong, as it literallay has no code: 

```
import mdfreader
yop = mdfreader.mdf('2015-09-29_10-53_JLR_Busbartest_50degC_000.MDF') # loads whole mdf file content in yop mdf object
yop.keys() # list channels names
yop.masterChannelList() # list channels grouped by raster or master channel
yop = mdfreader.mdfinfo() # create a mdfinfo instance
yop.listChannels('2015-09-29_10-53_JLR_Busbartest_50degC_000.MDF') # returns the list of channels
```

But when i execute the code i get an error when trying to list the channels:
```
runfile('D:/usr/bla/mdfopener.py', wdir='D:/usr/bla/')
2015-09-29_10-53_JLR_Busbartest_50degC_000.MDF
Traceback (most recent call last):

  File "<ipython-input-5-0536134f7c94>", line 1, in <module>
    runfile('D:/usr/bla/mdfopener.py', wdir='D:/usr/bla/Arbeit/CAE/E33/E33_Busbartest')

  File "D:\usr\bla\Apps\PortableApps\WinPython-64bit\python-3.4.4.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 845, in runfile
    execfile(filename, namespace)

  File "D:\usr\bla\Apps\PortableApps\WinPython-64bit\python-3.4.4.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 103, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/usr/bla/mdfopener.py", line 18, in <module>
    yop.masterChannelList() # list channels grouped by raster or master channel

TypeError: 'dict' object is not callable
```

What is it what iam doing wrong? i really cant figure out whats wrong :( 

Sincerely,
Blubbsy

**Comment by ratal** [comment]
.masterChannelList is an attribute, not a method. It means that yop.masterChannelList will work (without the parenthesis)
masterChannelList contains a representation of your rasters (keys are master channels and values a list of channels related to this raster)
.keys() will list all the channels (including master channels)
If you want to list the channels without loading all the data, you can do as you started to write using mdfinfo class.

**Comment by ratal** [comment]
I guess you understood the mistake since then, closing this issue.
