### ISSUE TITLE
Issue with mdfreader

### ISSUE THREAD

**Issue by HemanthMChakravarthy** [ratal/mdfreader#38]
Hello Ratal,
I have installed this python package to read an mdf file and export to a CSV file.
When trying to read it "yop=mdfreader.mdf('NameOfFile')"
I am getting the following error. Kindly look into it and let me know the problem, that could be.

log:
<FHcomment>
<TX>Min/max values changed</TX>
<tool_id>CANape</tool_id>
<tool_vendor>Vector Informatik GmbH</tool_vendor>
<tool_version>11.0.70.53107</tool_version>
<user_name>Hemanth</user_name>
</FHcomment>>
Traceback (most recent call last):
  File "C3PO_Trials.py", line 20, in <module>
    yop=mdfreader.mdf('XXXMeasurementXXX.MDF')
  File "/usr/local/lib/python2.7/dist-packages/mdfreader/mdf.py", line 106, in __init__
    self.read(fileName, channelList=channelList, convertAfterRead=convertAfterRead, filterChannelNames=filterChannelNames)
  File "/usr/local/lib/python2.7/dist-packages/mdfreader/mdfreader.py", line 353, in read
    self.read4(self.fileName, info, multiProc, channelList, convertAfterRead, filterChannelNames=False)
  File "/usr/local/lib/python2.7/dist-packages/mdfreader/mdf4reader.py", line 1352, in read4
    temp.loadInfo(info)  # load all info related to record
  File "/usr/local/lib/python2.7/dist-packages/mdfreader/mdf4reader.py", line 1034, in loadInfo
    self.recordToChannelMatching[Channel.name] = self.recordToChannelMatching[self[-2].name]
KeyError: u'_build_id'

**Comment by ratal** [comment]
Sorry, I do not have enough information to investigate your issue, I do not know what could be the error.
2 possible ways for me to support you:
- Send the file if it is not confidential for you
- Send an .xml representation of your file structure using mdfvalidator from vector you can download freely from their website.

**Comment by HemanthMChakravarthy** [comment]
Hello ratal, 
I am sorry, for some confidential reasons, i can send you the mdf files, I am using. 
Nevertheless, you can send me the mdf file or download link of that file, so that i can check if it is actually working in my pc with other mdf files. 
If it still doesn't work, then you can help me in debugging the issue, i guess. 
Please support me, as i am working on a deadline to deliver a tool. Thank you

**Comment by HemanthMChakravarthy** [comment]
Sorry, small correction in above comment. I can not send you the mdf file I'm working on. 

Please send me any reference mdf that you are using.

**Comment by ratal** [comment]
Hi,
Please send me your email adress and I will send you some open reference files you could test.

**Comment by HemanthMChakravarthy** [comment]
Hello ratal,

I found the issue, I guess. The problem is that, my MDF file is too big to fit in as an object.
So, I have got some vector libraries, with the help of which I can set pointers to the channel groups, channels and records within MDF and read the data.
Thanks for your support. Im closing this issue.

**Comment by ratal** [comment]
Glad you could fix your issue.
By the way, mdfreader can cope with bug files by loading only the channels you need (channelList parameter) and not converting the data (storing raw data and its conversion method with convertAfterRead=False)
