### ISSUE TITLE
 mdfreader/mdfreader/mdfinfo3.py, mdfblockread3 stumbles if value == '', Python 3, 2?

### ISSUE THREAD

**Issue by jontis** [ratal/mdfreader#40]
value.decode does not work if value is a str, which it is if it is set to = '' as on row 653
tested on Python3.

suggested fix, only run block 654-663 if value != ''

**Comment by jontis** [comment]
659:                     elif value != ''::

**Comment by ratal** [comment]
Thanks for the proposal.
Next commit will be 
659:       elif value:
no need of !='' I think
