### ISSUE TITLE
import problem in mdfreader.py, readinfo

### ISSUE THREAD

**Issue by jontis** [ratal/mdfreader#41]
suggested change (inline with how you did some other imorts): 
           try:
                from .mdfinfo3 import info3
            except:
                from mdfinfo3 import info3

**Comment by ratal** [comment]
Indeed more consistent, thanks for the proposal.
You had issues at these lines ?

**Comment by jontis** [comment]
I had problems with the import. 
I think this post is detailing the issue and suggest nicer solutions, by completely removing the relative imports ans using absolute imports.
I'm just suggesting and not fixing and reorganizing the code as I'm not very good at writing modules...
http://stackoverflow.com/questions/16981921/relative-imports-in-python-3

**Comment by ratal** [comment]
Thanks for the proposal and the link, good idea. I will try to implement absolute import.

**Comment by ratal** [comment]
Should be done in latest commit.
