### ISSUE TITLE
Handles only Sorted MDF File?

### ISSUE THREAD

**Issue by ssd4130** [ratal/mdfreader#42]
I've been working on a python library that generates an MDF file from scratch, given the inputs for channel groups. I'm noticing that when I use Vector's MDF Validator tool I'm not getting any errors and all of my channel groups are recognized just fine. I am, however, producing _unsorted_ MDFs and am wondering if mdfreader only handles _sorted_ files?

When I try to upload an MDF using your package I am seeing a **KeyError: 'data'** error. [https://imgur.com/a/Bjapk](url) <-- Screenshot of console

Any ideas what this might be?

**Comment by ratal** [comment]
Indeed for version 3.x of mdf, mdfreader is able to read only sorted file, no unsorted. This is rarely used for version 3.x, you are the only one to have noticed it since years. Unsorted reading is however implemented for version 4.x and could be reused I think for version 3.x but quiet some work. Which tool generates your unsorted files ?
On top of that I have no unsorted mdf 3.x file to experiment with and develop code, that's the main reason why it's not implemented so far --> if you can share dummy files, I (or we if you feel courageous) could develop it.

**Comment by ssd4130** [comment]
I would be more than happy to provide you with an unsorted file! How could I send it to you? I'm also willing to make a seperate branch and push it to this remote repo so we can work on it together.

**Comment by ratal** [comment]
You can send the file to my mail address aymeric.rateau@gmail.com
If you want to propose code do not hesitate to send pull request from your branch.

**Comment by ratal** [comment]
I just implemented unsorted reading functions. Please try with your file or send it to me.

**Comment by smatti** [comment]
Hi ratal, I am facing the same issue: I  have an error: "KeyError: 'data'" when trying to read in an unsorted mdf3 file. I just updated my mdfreader from your rep and tried again. Key error 'data' is not generated, however it now fails with

  File "C:\Anaconda3\lib\site-packages\mdfreader\mdf3reader.py", line 684, in loadUnSorted
    stream = fid.read(self.dataBlockLength)
NameError: name 'fid' is not defined
unsorted

I am using python 3.5.2, Anaconda3 64 bit.
My Python-Script symply looks like:

import mdfreader
yop=mdfreader.info3()
list=yop.listChannels3('D:/tmp/test_V3p3.mdf')
print (list)         #hooray this works!
mdfreader.mdf(fileName='D:/tmp/test_V3p3.mdf', convertAfterRead=False)

**Comment by ratal** [comment]
I think I fixed this issue in last commit.
However, without sample file, it will take many iterations.

**Comment by ratal** [comment]
No news since almost a month, considered it is working implementation

**Comment by ssd4130** [comment]
Hey Ratal,

Sorry about my lack of activity lately. I've been in Germany doing a study abroad for school and have been using all of my free time finishing my school work and traveling. Give me a little bit and I will send you a sample unsorted MDF file.

**Comment by ratal** [comment]
Hi,
Do you still have opportunity to share unsorted file for troubleshooting ?
