### ISSUE TITLE
Data Type Conversion

### ISSUE THREAD

**Issue by redshim** [ratal/mdfreader#44]
Hello, 

If I use below script the VS data number of data have been cut. 
yop.exportToCSV(filepathToCsv)
value  : 2.500000000000000000e+01(exponential expression)
After using exportToCSV
this the record expressed 0.

Information have lost. Do you know how I can fix it? 

Best Regards,

**Comment by ratal** [comment]
I am not sure to understand your issue.
Which version of mdf are your dealing with ?
exportToCSV is using csv module from bare python, it does not contain any numeric manipulation, using numpy, so I do not see why this value changed.

**Comment by ratal** [comment]
I have found the bug in write3.
The numberOfBits considered was not correct in case of string array.
Give a try to latest commit

**Comment by redshim** [comment]
Thank you for your help!! :)
