### ISSUE TITLE
problem parsing metadata for CC block

### ISSUE THREAD

**Issue by swoldetsadick** [ratal/mdfreader#45]
problem parsing metadata for CC block
<CCcomment xmlns="http://www.asam.net/mdf/v4"><TX>Def_float</TX><common_properties><e name="format" type="string">%6.3f</e></common_properties></CCcomment>

I come up with this type of issue all the time while trying to read mdf data

**Comment by ratal** [comment]
Where do you have this error, what line ? It does not seem to be an error message.
By doing what exactly ?
With the same file or many other files ?

**Comment by swoldetsadick** [comment]
Same music data is confidential cannot be shared, but I will try the suggestions and get back
