### ISSUE TITLE
no channel.CFormat when reading mdf4

### ISSUE THREAD

**Issue by smatti** [ratal/mdfreader#60]
Hi, I am trying to read a sorted mdf4.1 with mdfreader version master0.2.4 from GITHub.
The following error is thrown:

>   File "C:\Anaconda2\lib\site-packages\mdfreader\mdf4reader.py", line 1128, in readSortedRecord
>   rec[channel.name][r] = channel.CFormat.unpack(buf[channel.posByteBeg:channel.posByteEnd])[0]
>   AttributeError: channel instance has no attribute 'CFormat'

I tracked that the error is caused, when it comes to read the channel 'ms', which is added to the channelList from the record.loadInfo() function.
Looking in the debugging mode into the channel objects, CFormat really does not exist for channel 'ms'. It exists only Format, which is however an empty string. This struct, CFormat, should be created in  channel.set() from channel.Format which has been set by datatypeformat4(). However, channel.set is never called for the added channel 'ms', so that Format remains empty and CFormat is never created.  
Channel.set() is called in line 990 in fct loadInfo() of class record and before channel ms is added.
For channel 'ms' (and 'hour, 'day', etc) the function channel.setCANOpen() is called. In this function Format is not filled by datatypeformat4() and CFormat is not created.
I added the following lines of code, which I copied from channel.set(), to the end of function channel.setCanopen():
`        if self.signalDataType not in (13, 14):  # processed by several channels
            if not self.channelType == 1:  # if not VSLD
                self.Format = datatypeformat4(self.signalDataType, self.bitCount)
            else:  # VLSD
                self.Format = datatypeformat4(0, self.bitCount)
        self.CFormat = Struct(self.Format)
`
The script then runs without throwing this error, but I still need to check if data Import works correctly ...

**Comment by ratal** [comment]
Thanks for pointing out this issue.
I made modfications in latest commit to add .Format and .CFormat in CANOpen channnels.
Please check.

**Comment by smatti** [comment]
Hi Ratal, thanks for the quick action. I tried the latest commit: with python 3.5 it works, but with 2.7 I get another issue, not directly connected to the CFormat topic, but with the additional time channels (ms, ...):

>   File "C:\Anaconda2\lib\site-packages\mdfreader\mdf4reader.py", line 1383, in read4
>    channelSet.add(['ms', 'minute', 'hour', 'day', 'month', 'year'])

I think it must rather be 
`channelSet.update(['ms', 'minute', 'hour', 'day', 'month', 'year'])`
instead of using set.add([])
When adding elements to a set, 'add' is used only for single items, 'update'  is used to add a list. Am I wrong?

**Comment by ratal** [comment]
Yes, indeed, it seems more correct but I do not understand why I could not catch it in my tests with CANopen data and python2.7
Anyway, modified in last commit, please check.

**Comment by ratal** [comment]
I consider it solved your issue. Do not hesitate to reopen if you have still same issue.
