### ISSUE TITLE
Get full name of channel

### ISSUE THREAD

**Issue by tivoodoo** [ratal/mdfreader#61]
Hi,

is it possible to get the full name of each channel?
I use `mdf.masterChannelList` to get the list of channels and then get name of channel from there. But the name are truncated by the last part after "\". 

For example channel with name `abcxyz\CME:1` will only show up as `abcxyz`

Sincerely

**Comment by ratal** [comment]
I guess you are reading mdf version 3.x ? (this should not happen in version 4.x I think)
If you comment line 178 of mdfinfo3, you should get the full name

**Comment by tivoodoo** [comment]
Hi ratal, I followed your advise and commented line 178 but possibly deviceName is used at another places as well. So the program returned error when reading mdf.

But you pointed me to the right direction, so I made a quick fix:

``` python
                    fullname = signalname
                    signalname = signalname.split('\\')
                    if len(signalname) > 1:
                        self['CNBlock'][dataGroup][channelGroup][channel]['deviceName'] = signalname[1]
                    signalname = fullname
```

The correct solution must be include one more variable/function to get full name. I'll try to contribute to the code base when I learn more about python

**Comment by ratal** [comment]
Yes, feel to submit a pull request !
