### ISSUE TITLE
yop.masterChannelList()  TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by jontis** [ratal/mdfreader#65]
mdfConverter can read and conver the file.

yop.masterChannelList()
Traceback (most recent call last):

  File "<ipython-input-8-12914802972f>", line 1, in <module>
    yop.masterChannelList()

TypeError: 'dict' object is not callable

**Comment by ratal** [comment]
Hi Jontis,
I guess mdfconverter cannot read your file.
I have too little information from trace to help you. Can you post everything please ?
Also what version are you using and environment info like python and pyqt version ?

**Comment by jontis** [comment]
mdfconverter seems to read and convert the file fine (I think, I used it as a test to convert the file).
It is mdfreader, used exactly as in the readme example that can't read the file.
The file seems to be correctly loaded into mdfreader, and several functions work fine, but not method mdfreader.

**Comment by jontis** [comment]
I'd be happy to post more information if you point me in the right direction. There is so much of it.

**Comment by ratal** [comment]
CAn you show an extract of your code using mdfreader ?
mdfreader is a moduel by the way, not a method ?

**Comment by jontis** [comment]
This is my code: from the readme
>>> import mdfreader
>>> yop=mdfreader.mdf('NameOfFile') # loads whole mdf file content in yop mdf object
>>> yop.keys() # list channels names
>>> yop.masterChannelList() # list channels grouped by raster or master channel

Three first lines work great. yop.masterChannelList() does not.

**Comment by ratal** [comment]
Sorry for this, masterChannelList attribute is a list, so no () at the end:
yop.masterChannelList short will work

**Comment by jontis** [comment]
Ok, that works.

A further comment is that it is not a list, it is a dict. Sorry bout the particulars but that naming causes confusion.
