### ISSUE TITLE
improvement - README line endings

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#69]
the README file has currently Windows line endings (CRLF).
If you save it with UNIX line endings (LF) the restructured text will be correctly displayed in Github and PyPI

**Comment by ratal** [comment]
Improved, should be better rendered now.

**Comment by danielhrisca** [comment]
I think you should also update setup.py with the new readme file name

**Comment by ratal** [comment]
Indeed, thanks.
