### ISSUE TITLE
bug: wrong output in mdf version3 

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#73]
Using the test.mdf file, for the channel _FAIL_RAM_MEM_21_ the output from mdfreader 0.2.5 is
![fail_ram_mem_21_nok](https://user-images.githubusercontent.com/20952040/28608967-4d85c562-71eb-11e7-8d48-93c5024cfb3d.png)
and it should be
![fail_ram_mem_21_ok](https://user-images.githubusercontent.com/20952040/28608976-56ba376c-71eb-11e7-803c-cb64ebf201e0.png)

(Python 3.4.4 32 bit, mdfreader 0.2.5, numpy 1.11.3)

**Comment by ratal** [comment]
Definitely, I do not understand what is your environment difference with mine that could cause this error.
I could not reproduce your issue, I have what you expected.
exact try from my side:
python 3.5.3 64bit, python 2.7.13 64bit, numpy 1.11.2, debian
I will try on windows environment with anaconda

**Comment by danielhrisca** [comment]
I only use WinPython distributions on Windows (7 x64 and 10 x64).

**Comment by ratal** [comment]
I tried with anaconda on win10 and python 3.6.0 64bit, anaconda 4.3.1, numpy 1.11.3 and I could not reproduce your issue.

**Comment by danielhrisca** [comment]
WinPython uses numpy compiled with Intel MKL library. Maybe this could be the root cause. I'll check to see if regular numpy works correctly.

**Comment by danielhrisca** [comment]
I've tried this on Ubuntu, and I still get an error:

* 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
* Linux-4.10.0-19-generic-i686-with-Ubuntu-17.04-zesty
* i686
* 4GB installed RAM
* numpy 1.13.1 from PyPI
* mdfreader 0.2.5 from PyPI

![image](https://user-images.githubusercontent.com/20952040/28765114-addc37b8-75d1-11e7-8dbd-aa6d76865013.png)

**Comment by ratal** [comment]
I am a bit puzzled. Are you testing the same file that you sent me ?

**Comment by danielhrisca** [comment]
It's the same file attached to issue #67

**Comment by ratal** [comment]
ok, I'll test with winPython on Windows

**Comment by ratal** [comment]
I tried on win10 with winPython 3.5.3 zero and installed from [pythonlibs](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy-stack) numpy with mkl and I could not reproduce your issue.
I also tried with winPython 3.6.1 complete, I could not also reproduce your issue.
Sorry I am a bit stuck there. Are you sure you did not do any modification to the code ?

**Comment by danielhrisca** [comment]
Well I've installed WinPython on two different machines and I get this issue. 
One a third machine with Ubuntu I've pip installed mdfreader and again I get the issue.
To make sure I'm using the 170 MB with 36424 channels.

**Comment by ratal** [comment]
I am using virtualbox for win10 on the same machine but I doubt this could be the reason I cannot reproduce, considering you have also this problem with ubuntu.
I also tried on another machine with ubuntu, still I cannot reproduce.
I think we are trying with the same file, same number of channels (a lot) but just in case, the one you sent me has 192.5Mo ?
Also I do not use pip but rather python setup.py develop in the source folder.

**Comment by danielhrisca** [comment]
Then it is not the same file. It should be a mdf version 3 file of 170MB. If you extract again the attachment from issue #67 you will have the correct file.

**Comment by ratal** [comment]
ok, good news, I can reproduce and will investigate

**Comment by ratal** [comment]
Hi,
Last commit should have solved this issue and #74 
Can you check it ?

**Comment by danielhrisca** [comment]
Hi, I will try this next week

**Comment by danielhrisca** [comment]
Hello Aymeric,

the latest master solves this issue.
