### ISSUE TITLE
error getting channels with option noDataLoad from mdf version 3 test file

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#79]
I tried to use the newly introduced _noDataLoad_ option

using commit c7d1860

using bench script https://github.com/danielhrisca/asammdf/blob/development/benchmarks/bench.py

I get this error when getting channels from mdf version 3 file:

```
Traceback (most recent call last):
  File "d:\WinPython-64bit-3.6.2.0Qt5b3\python-3.6.2rc1.amd64\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "d:\WinPython-64bit-3.6.2.0Qt5b3\python-3.6.2rc1.amd64\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Work\asammdf\benchmarks\bench.py", line 213, in get_all_reader3_nodata
    y = x.getChannelData(s)
  File "d:\WinPython-64bit-3.6.2.0Qt5b3\python-3.6.2rc1.amd64\lib\site-packages\mdfreader\mdfreader.py", line 441, in getChannelData
    return self._getChannelData3(channelName)
  File "d:\WinPython-64bit-3.6.2.0Qt5b3\python-3.6.2rc1.amd64\lib\site-packages\mdfreader\mdf3reader.py", line 1024, in _getChannelData3
    return self._convert3(channelName)
  File "d:\WinPython-64bit-3.6.2.0Qt5b3\python-3.6.2rc1.amd64\lib\site-packages\mdfreader\mdf3reader.py", line 1042, in _convert3
    vect = self[channelName][dataField][:]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ratal** [comment]
Hi Daniel,
Thanks for reporting, indeed an issue there, introduced of new features are not tested enough.
Should be fixed with latest commit.

**Comment by danielhrisca** [comment]
Hello Aymeric,

the issue is fixed and mdfreader works faster when saving:


Benchmark environment

-   3.6.2rc1 (heads/3.6:268e1fb, Jun 17 2017, 19:01:44) \[MSC v.1900 64 bit (AMD64)\]
-   Windows-10-10.0.15063-SP0
-   Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
-   16GB installed RAM

Notations used in the results

-   nodata = MDF object created with load\_measured\_data=False (raw channel data not loaded into RAM)
-   compression = MDF object created with compression=blosc
-   compression bcolz 6 = MDF object created with compression=6
-   noDataLoading = MDF object read with noDataLoading=True

Files used for benchmark: \* 183 groups \* 36424 channels

| Open file                           | Time \[ms\] | RAM \[MB\] |
|-------------------------------------|-------------|------------|
| mdfreader 0.2.6 mdfv3               | 3698        | 542        |
| mdfreader 0.2.6 compression mdfv3   | 5041        | 262        |
| mdfreader 0.2.6 noDataLoading mdfv3 | 1933        | 193        |
| mdfreader 0.2.6 mdfv4               | 42596       | 1315       |
| mdfreader 0.2.6 compression mdfv4   | 46789       | 1027       |
| mdfreader 0.2.6 noDataLoading mdfv4 | 5001        | 948        |

| Save file             | Time \[ms\] | RAM \[MB\] |
|-----------------------|-------------|------------|
| mdfreader 0.2.6 mdfv3 | 7925        | 541        |
| mdfreader 0.2.6 mdfv4 | 4065        | 1315       |

| Get all channels (36424 calls) | Time \[ms\] | RAM \[MB\] |
|--------------------------------|-------------|------------|
| mdfreader 0.2.6 mdfv3          | 90          | 541        |
| mdfreader 0.2.6 mdfv4          | 97          | 1315       |
