### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by themeadowsguy** [ratal/mdfreader#8]
When I install using setup.py, the file does not show up as accessible unless running code from the cloned directory.  Install via pip or setup.py should install the necessary files into the site-packages folder without the need to run the code within the git-cloned directory.

**Comment by ratal** [comment]
This is my first project on pypi. I looked at documentation and I was not building universal wheel as it should be. I upload new version 0.1.3 -> can you try again with pypi ?

**Comment by ratal** [comment]
0.1.3 was probaly not ok, I changed for a more correct folder structure with __init__.py in 0.1.4
mdfreader should be working, can you try ?
However, mdfconverter is another matter. I do not know yet how to make it launchable from command line.

**Comment by themeadowsguy** [comment]
I will try tomorrow.

Eric

Sent from my iPhone

On May 25, 2015, at 10:05 AM, Aymeric Rateau <notifications@github.com<mailto:notifications@github.com>> wrote:


0.1.3 was probaly not ok, I changed for a more correct folder structure with init.py in 0.1.4
mdfreader should be working, can you try ?
However, mdfconverter is another matter. I do not know yet how to make it launchable from command line.

**Comment by themeadowsguy** [comment]
It installed properly.
