### ISSUE TITLE
wrong hanling of bit offset for embeded channels in mdf version 3

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#80]
Using the test file and plotting _Fsf_pres_sens_rla_

it should be:

![image](https://user-images.githubusercontent.com/20952040/29494482-f4db3bfe-85b3-11e7-8b47-6a910c781411.png)

but mdfreader plots:

![image](https://user-images.githubusercontent.com/20952040/29494494-1df2eabe-85b4-11e7-86d0-887743d7614c.png)

I think the error comes from the fact that when loading the record info, the parent channel is a 16 bit channel, and this channel has a bit offset of 8 relative to the parent channel, while in the conversion the bit offset is computed from the offset in the channel group record , resulting in a bit offset of 0.

**Comment by ratal** [comment]
Hi Daniel,
Last commit should fix this.

**Comment by danielhrisca** [comment]
Hello Aymeric,

this issue is solved.
