### ISSUE TITLE
errors in files written by mdfreader

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#84]
Loading and saving the test files to disk:
```python
from mdfreader import mdf

x = mdf(r'D:\TMP\test.mf4')

x.write(r'D:\TMP\x.mf4')

x = mdf(r'D:\TMP\test.mdf')

x.write(r'D:\TMP\x.mdf')
```

gives for version 3:

![image](https://user-images.githubusercontent.com/20952040/30220887-f01a1b1a-94c9-11e7-8d39-2edb1a0bc22d.png)

and for version 4:

![image](https://user-images.githubusercontent.com/20952040/30220894-fab02b8c-94c9-11e7-8152-fe947d292a8a.png)

**Comment by ratal** [comment]
Hi Daniel,
There was a minor bug in mdf4 write (wrong pointer address).
And I refactored mdf 3 write, there should not be any error and performance improved. Still some warnings related to channel name not being conform with ASAP2.

**Comment by danielhrisca** [comment]
hello Aymeric,

there are still some errors:
```python
mdfreader 0.2.6 mdfv3                                    145      507
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/daniel/.config/spyder-py3/temp.py", line 213, in save_reader3
    x.write(r'x.mdf')
  File "/usr/lib/python3.6/site-packages/mdfreader/mdfreader.py", line 422, in write
    self.write3(fileName=self.fileName)
  File "/usr/lib/python3.6/site-packages/mdfreader/mdf3reader.py", line 1386, in write3
    fid.write(pack('<2sH5IH32s128s4H3d2IH', *head))
struct.error: argument for 's' must be a bytes object
```

**Comment by ratal** [comment]
just fixed it, I did first tests with python2, forgot python3

**Comment by danielhrisca** [comment]
I still get the error.

**Comment by ratal** [comment]
Are you on commit 36dfe4a ?

**Comment by danielhrisca** [comment]
Yes, I've installed the latest commit after your previous comment

**Comment by ratal** [comment]
fid.write(pack('<2sH5IH32s128s4H3d2IH', *head)) is for me line 1391 ?

**Comment by danielhrisca** [comment]
Forgot to add -U parameter to pip

For version 3 now it complains about strings not being correctly terminated

![image](https://user-images.githubusercontent.com/20952040/30293537-92b715ec-9742-11e7-8b6d-d5ea00ca225e.png)

**Comment by ratal** [comment]
Just fixed it in last commit.
ASAP2 names remain non conform as in original file.

**Comment by danielhrisca** [comment]
fixed
