### ISSUE TITLE
missing information when saving to version 4 with noDataLoading=True

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#86]
Some important information is missing from the channels when saving to mdf version 4 noDataLoading=True:
* channel unit
* channel min/max values
* channel comment

For example the signal _MAIN_CLOCK_ from the test file:

![image](https://user-images.githubusercontent.com/20952040/30243709-94b2f888-95b8-11e7-9413-0ac2379beee8.png)
![image](https://user-images.githubusercontent.com/20952040/30243715-aed74c1e-95b8-11e7-87ea-0ea1d9bbd584.png)

and the saved file has:

![image](https://user-images.githubusercontent.com/20952040/30243721-c4ef6752-95b8-11e7-8048-0f9ed30d2d52.png)

**Comment by danielhrisca** [comment]
with the latest commit the information are missing for all mdf options (nodataloading, compression, default)

**Comment by ratal** [comment]
Yes, I also noticed a regression there, investigating

**Comment by danielhrisca** [comment]
fixed
