### ISSUE TITLE
Wrong type of ev_sync_base_value

### ISSUE THREAD

**Issue by ro-gro** [ratal/mdfreader#89]
As described within the ASAM MDF 4.1 document, the type of ev_sync_base_value is INT64, but you use UINT64.

mdfinfo4.py - line 995:
self['ev_sync_base_value'] = self.mdfblockread(fid, UINT64, 1)

Therefore negative event times are wrong.

**Comment by ratal** [comment]
Hi ro-gro,
Thanks for spotting it out.
It should already be fixed in latest commit, you can have a look or wait for the next release that should come soon.

**Comment by ro-gro** [comment]
Hi ratal,

thank you for the fast reaction. I tested the latest version and it works well.
