### ISSUE TITLE
Unable to convert MDF to .m

### ISSUE THREAD

**Issue by DavidBaumg** [ratal/mdfreader#9]
The console always shows an error, when trying to convert the mdf file to .m - converting to csv works fine

Operating system: Win 7, 64 Bit. 
Converter version: newest, freshly pulled

Error code:
Error, following file might be corrupted : /cygdrive/d/testHILAPI/stress_test-08_06_2015-11_32_21.MDF
Traceback (most recent call last):
  File "/cygdrive/C/mdfreader-master/mdfconverter/mdfreaderui.py", line 111, in on_Convert_clicked
    result = list(map(processMDFstar, args))
  File "/cygdrive/C/mdfreader-master/mdfconverter/mdfreaderui.py", line 333, in processMDFstar
    raise Exception('Please re-try by removing this file from the list and restart mdfconverter to kill processes and clean memory')
Exception: Please re-try by removing this file from the list and restart mdfconverter to kill processes and clean memory

As stated in Response - I set MultiProc to False

The specific file mentioned in the Error can be sent via Mail/Link if necessary for testing purposes.

Regards David (Argyll)

**Comment by ratal** [comment]
Dear David,
Putting MultiProc to False did not really improve the error messages.
If you have the possibility to send your files, it will help to troubleshoot this concern.
Regards
Aymeric

15 juin 2015 10:15 "DavidBaumg"  a écrit:
	The console always shows an error, when trying to convert the mdf file to .m - converting to csv works fine

	Operating system: Win 7, 64 Bit.
Converter version: newest, freshly pulled

	Error code:
Error, following file might be corrupted : /cygdrive/d/testHILAPI/stress_test-08_06_2015-11_32_21.MDF
Traceback (most recent call last):
File "/cygdrive/C/mdfreader-master/mdfconverter/mdfreaderui.py", line 111, in on_Convert_clicked
result = list(map(processMDFstar, args))
File "/cygdrive/C/mdfreader-master/mdfconverter/mdfreaderui.py", line 333, in processMDFstar
raise Exception('Please re-try by removing this file from the list and restart mdfconverter to kill processes and clean memory')
Exception: Please re-try by removing this file from the list and restart mdfconverter to kill processes and clean memory

	As stated in Response - I set MultiProc to False

	The specific file mentioned in the Error can be sent via Mail/Link if necessary for testing purposes.

	Regards David (Argyll)

**Comment by DavidBaumg** [comment]
https://www.dropbox.com/s/2nqmd17lcxnc8hi/stress_test-08_06_2015-11_32_21.MDF?dl=0
one of our smaller samples (we are going up to 6+ GB Log files)
and thanks in advance

**Comment by ratal** [comment]
I tried to reproduce your concern on my linux environment with mdfreader in ipython and mdfconverter, using the file you made available but everything went ok.
I will try on win7 64 bit environment.
If you are courageous and want to try, for big data I made optional conversion of channels, keeping normally lot of memory with measurement data. For that, you can in mdfreaderui.py, line 302 change convertAfterRead attribute from True to False.
I would also advise to change your conversion format from .mat to .hdf5 Matlab is able to read it and writing process should consume less memory.

**Comment by ratal** [comment]
I also tried in win7 64 bit, no concern with your file.
Error message does not help there. It was supposed to help lambda user but for troubleshooting, not helpful. Can you make a try by removing the try: except: part around line 333 in mdfreaderui.py and keeping the return processMDF(args*) ? I hope error will be more understandable

**Comment by DavidBaumg** [comment]
Thanks a lot for your help! The removing of the except part gave the necessary hint. Somehow Cygwin was not able to use the 'scipy' library of python. After several hours of reinstalling i got it to work (I installed 'Anaconda' and set the PATH). I was now successfully able to convert a smaller file from mf4 (mdf) to mat. I'm currently running the 3GB file as a test.
So in the end it looks like your code is working fine and the problem was at my setup!

**Comment by DavidBaumg** [comment]
One last question though: how long would you estimate the time needed for converting a 3GB file? Since there is no progress status or something similar. I have the process running since 1.5hrs now without any outcome.
Best regards

**Comment by ratal** [comment]
Glad to hear it is working. For your big file, do you see your .mat file increasing in size ?
Otherwise, you can try to open it using ipython instead of mdconverter command line. It will allow you to split conversion in 2 steps : 1. loading in memory the data (blob=mdfreader.mdf('file.mf4') ) 2. blob.exportToMat()
Generally, processing speed will largely depend on how your data are structured.
If you still have problems, you can refer to my previous post about memory optimisation.

**Comment by ratal** [comment]
I checked with a mdf3 1Gb file and it takes around 10 sec on a core i7 920 with 6Gb of memory.
If your mdf4 contains new features from mdf4 like compressed data, Variable Length Signal Data, data that do not fit on ctype bytes or not byte aligned, unsorted data -> parsing of the data will be done record by record iteratively in python (not using recarray fromstring or fromfile that are super fast coded C).
Code can always be optimised but as there are many parts that can be improved, can you tell me from the above list which kind of data is most likely slowing you down ?
For that you can analyse your file using mdfvalidator freely downloadable from vector site (maybe you can export it into .xml)
If you have the possibility, the other solution is that you send me your big file on my server, we can have then private communication for that.

**Comment by DavidBaumg** [comment]
I downloaded the mdfvalidator and it turned out, that our file somehow got corrupted. Right now I'm running a sequence of stress-tests to see how big we can go with the MemoryWriter and the MDF4Writer. So I will be able to test the converter again on monday.
Regarding the private communication: I may have a few other questions regarding your code and it might not really fit the category "issues" so if you got the time, please send me an email to david.baumgartner[at]tuwien.ac.at
Thanks in advance

**Comment by ratal** [comment]
I think the original concern is solved now, I close this issue<
