### ISSUE TITLE
multiple mdfreader versions on same python installation

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#91]
Hello Aymeric,

currently it is impossible to have multiple mdfreader version on the same python installation since you append to sys,path 

I was able to get this to work by removing all sys.path appends and using relative imports; for example in ___init__.py_

```python
__author__ = 'Aymeric Rateau (aymeric.rateau@gmail.com)'
__copyright__ = 'Copyright (c) 2015 Aymeric Rateau'
__license__ = 'GPLV3'
__version__ = "0.2.6"

from .mdfreader import mdf, mdfinfo
from .mdf import mdf_skeleton
from .mdf3reader import mdf3
from .mdf4reader import mdf4
from .mdfinfo3 import info3
from .mdfinfo4 import info4, ATBlock  # ,MDFBlock
```

Anyway, it looks like a little competition can lead to improvements:

Benchmark environment

* 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
* Windows-10-10.0.15063-SP0
* Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
* 16GB installed RAM

Files used for benchmark:

* 183 groups
* 36424 channels

|Open file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|mdfreader 0.2.5 mdfv3                             |     4010|     534|
|mdfreader 0.2.6 mdfv3                             |     3659|     532|
|mdfreader 0.2.5 mdfv4                             |    45017|     745|
|mdfreader 0.2.6 mdfv4                             |     9589|     746|

|Save file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|mdfreader 0.2.5 mdfv3                             |    28196|    1994|
|mdfreader 0.2.6 mdfv3                             |     7453|     564|
|mdfreader 0.2.5 mdfv4                             |    25488|    2792|
|mdfreader 0.2.6 mdfv4                             |     6736|     768|

|Get all channels (36424 calls)                    |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|mdfreader 0.2.5 mdfv3                             |       45|     534|
|mdfreader 0.2.6 mdfv3                             |       93|     533|
|mdfreader 0.2.5 mdfv4                             |       60|     746|
|mdfreader 0.2.6 mdfv4                             |      100|     747|

**Comment by ratal** [comment]
Hi Daniel,
I was using originally using relative imports but I implemented absolute path import to support issue #41 . Seems more robust for various platforms and configurations but yes can probably cause issue if you want to have several versions compared.
Maybe using python environments should be more handy ?

**Comment by danielhrisca** [comment]
If you use it as a package then there are no problems with relative imports.

If you run a module from the package then you might have errors with relative imports.

**Comment by danielhrisca** [comment]
Is there any case in which a _mdfreader_ module is executed?

**Comment by ratal** [comment]
yes if you mean:
`python filename.mf4 --export HDF5 `

**Comment by danielhrisca** [comment]
The system.path is getting cluttered with all the appends down in various mdfreader modules.

But if no one else is complaining the this can be closed.
