### ISSUE TITLE
Mixed up signals values in 0.2.6

### ISSUE THREAD

**Issue by SubspaceBob** [ratal/mdfreader#94]
I have an issue with 0.2.6 not found in 0.2.5 where one signal gets the same values as another signal with very similar name. Using 0.2.5 I get the correct values.
![capture](https://user-images.githubusercontent.com/28918132/31463965-2b9aa3e2-aed0-11e7-8838-7c6544484d93.PNG)
[error.zip](https://github.com/ratal/mdfreader/files/1377033/error.zip)

Using python2.7 32bit on Windows. Thanks for an awesome tool!

**Comment by meisterlumpi** [comment]
Actually, I had this exact issue with 0.2.5. With 0.2.6 it seems to be fixed. Didn't do extensive testing yet, though..

**Comment by danielhrisca** [comment]
in 0.2.5 there was a problem with overlapping channels 

see issue #80

**Comment by SubspaceBob** [comment]
Anyone can feel free to try the read the dat-file, included in the error.zip together with a small script for creating two plots. The two plots should not be equal...

**Comment by danielhrisca** [comment]
Indeed seems to be a new issue in 0.2.6

# xVcScADrvrDesDir_B_Lvr2TipUp
![image](https://user-images.githubusercontent.com/20952040/31551631-d52d5fbc-b03d-11e7-83ef-893a59953321.png)

vs corect

![image](https://user-images.githubusercontent.com/20952040/31551697-ffbe8666-b03d-11e7-99c6-86f11e765c9e.png)

# xVcScADrvrDesDir_B_Lvr2TipDown
![image](https://user-images.githubusercontent.com/20952040/31551642-dcb45542-b03d-11e7-84dd-3c06f1417882.png)

vs correct

![image](https://user-images.githubusercontent.com/20952040/31551710-0f87631a-b03e-11e7-9135-c1678c02c7d6.png)

**Comment by ratal** [comment]
Hi,
there was an error calculating channel.embedding_channel_bitOffset
Indeed this part of the code computing bit channels was completly reviewed for 0.2.6
Last commit should fix it, can you try ?

**Comment by ratal** [comment]
Is it solved for everybody ?

**Comment by SubspaceBob** [comment]
I have not the ability to test the change until it is included into a new
wheel on pypi. Thanks for your effort!!

2017-11-02 23:33 GMT+01:00 Aymeric Rateau <notifications@github.com>:

**Comment by ratal** [comment]
I pushed new release in pypi, you can have a try

**Comment by SubspaceBob** [comment]
This issue is fixed in 0.2.7, but the signals don't have the correct name when printing the keys(), the names are signalname_0 or signalname_1. They are appended by a _0 or _1. Why is that? So i'm sticking with 0.2.5 for a while longer. Should i confirm this as solved an create a new issue??

I also tried 2.7.1 but got: 
ImportError: cannot import name getlogin
What is this? Running 2.7.14

**Comment by cristi-neagu** [comment]
The channel name issue has been flagged and solved in #105.

**Comment by danielhrisca** [comment]
mdfreader version went from 0.2.7 to 2.7.1

**Comment by ratal** [comment]
You could try last commit, I fixed it I think.
getlogin is only available for unix platform, I introduced this condition for import and usage.
