### ISSUE TITLE
cc_val can be scalar

### ISSUE THREAD

**Issue by meisterlumpi** [ratal/mdfreader#95]
mdf4reader.py --> valueToTextConv()
first line:
`val_count = int(len(cc_val))` will fail if cc_val is a scalar (float)
suggestion:
`if isinstance(cc_val, (list, tuple)):`
`  val_count = int(len(cc_val))`
`else:`
`  val_count = int(1)`

**Comment by ratal** [comment]
Hi,
Please try latest commit, valueToTextConv() has been compeltely reworked for issue #59

**Comment by ratal** [comment]
I guess it worked ?
No feedback since a while, I close, feel free to repoen
